export const Colors = {
  light: {
    text: "#000000",
    background: '#FFFFFF',
    brandColor1: '#44B88A',
    brandColor2: '#4F41D8',
    secondaryShade: '#F8F8F8',
    androidSecondaryShade: '#EFEFEF',
    unselectedText: '#D5D4DD',
    normalIconColor: '#000000',
    alertColor: '#FF3B30',
    graphLineColor: '#E5E4EA',
  },
  dark: {
    text: "#FFFFFF",
    background: '#1A1A1A',
    brandColor1: '#44B88A',
    brandColor2: '#4F41D8',
    secondaryShade: '#2A2A2A',
    androidSecondaryShade: '#2A2A2A',
    unselectedText: '#D5D4DD',
    normalIconColor: '#FFFFFF',
    alertColor: '#FF3B30',
    graphLineColor: '#E5E4EA',
  },
};
