export const strings: Record<string, any> = {
  English: {
    // AddDeckModal strings
    addFlashcardsToDeck: 'Add Flashcard(s) to Deck',
    addDeckToFavorites: 'Add Deck to Favorites',
    addDeckToFolder: 'Add Deck to Folder',
    addDeck: 'Add Deck',
    genAIForm: 'Gen AI Form',
    fileUpload: 'File Upload',
    youtubeLink: 'YouTube Link',
    manual: 'Manual',
    // InterviewStudyToggle strings
    study: 'Study',
    interview: 'Interview',
    // AIDeckCard strings
    cardTypes: {
      behavioral: 'Behavioral',
      technical: 'Technical',
      brainteasers: 'Brainteasers',
      'case study': 'Case Study',
      others: 'Others',
      study: 'Study',
    },
    cards: 'cards',
    // Card component strings
    progress: 'progress',
    completed: 'Completed!',
    untitledDeck: 'Untitled Deck',
    // AIPromptModal strings
    aiPromptTitle: 'Try these AI Decks created just for you!',
    loadingAiDecks: 'Loading AI decks...',
    noDeckSuggestions: 'Oops! No deck',
    noDeckSuggestionsSubtitle: 'suggestions for now',
    emptyStateFooter: 'We\'ll generate more',
    emptyStateFooterSubtitle: 'as you practice more!',
    // FolderCard strings
    decks: 'decks',
    // FormHeaderIcons strings
    clearAll: 'Clear All',
    // KindsOfQuestions strings
    kindsOfQuestionsTitle: '4. What kinds of questions do you want to practice more of? (Pick any)',
    questionTypes: {
      recall: 'Recall',
      comprehension: 'Comprehension',
      application: 'Application',
      analysis: 'Analysis',
      synthesis: 'Synthesis',
      evaluation: 'Evaluation',
      problemSolving: 'Problem-Solving',
    },
    // QuestionTextBarWithDropdown strings
    companiesStartingWith: 'Companies starting with',
    selectACompany: 'Select a company',
    noCompaniesFoundStartingWith: 'No companies found starting with',
    noCompaniesFound: 'No companies found',
    loadingCompanies: 'Loading companies...',
    // TypeOfInterviewQn strings
    typeOfInterviewTitle: '2. Which kind of interview are you preparing for? (Pick One)',
    interviewTypes: {
      technical: 'Technical',
      behavioral: 'Behavioral',
      brainteasers: 'Brainteasers',
      caseStudy: 'Case Study',
      others: 'Others',
    },
    // ActionButtonsRow strings
    cancel: 'Cancel',
    // BottomTextInputModal strings
    editDeckName: 'Edit deck name',
    done: 'Done',
    // DifficultyToggleRow strings
    difficultyOptions: {
      default: 'Default',
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
    },
    // HeaderIconButtons strings
    searchPlaceholders: {
      decks: 'Search for Decks',
      folders: 'Search for Folders',
      favorites: 'Search Favorites',
      default: 'Search',
    },
    sortOptions: {
      name: 'Name',
      dateAdded: 'Date Added',
      lastModified: 'Last Modified',
    },
    // NavBar strings
    navItems: {
      account: 'Account',
      decks: 'Decks',
      statistics: 'Statistics',
      awards: 'Awards',
      stats: 'Stats',
    },
    // SlidingMenu strings
    viewFolders: 'View Folders',
    viewFavorites: 'View Favorites',
    // AddViewToggle strings
    addFlashcards: 'Add Flashcard(s)',
    viewFlashcards: 'View Flashcard(s)',
    // DrawableOptionsRow strings
    clear: 'Clear',
    // FlippableCard strings
    typeHere: 'Type here!',
    drawHere: 'Draw here!',
    pressHoldMic: 'Press & hold mic \nbutton to record',
    greatReplay: 'Great! Click the replay\nbutton below to play\nthe recorded audio!',
    clickToTakeOrUpload: 'Click here to take\nyour picture or\nupload from library!',
    chooseManual: 'Choose your manual \noption above',
    cameraPermissionError: 'Sorry, we need camera permissions to make this work!',
    photoLibraryPermissionError: 'Sorry, we need camera roll permissions to make this work!',
    imageSelectionError: 'Error selecting image. Please try again.',
    photoCaptureError: 'Error taking photo. Please try again.',
    // CalendarModal strings
    calendarSubtitle: 'Press "Done" or "Choose Date" to apply your selection.',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    all: 'All',
    chooseDate: 'Choose Date',
    // GenericModal strings
    no: 'No',
    yes: 'Yes',
    ok: 'OK',
    // TabLayout strings
    deleteDecksConfirmation: 'Are you sure you want to delete these deck(s)?',
    noSelectionMade: 'No selection made!',
    noSelectionSubtitle: 'Please choose at least one deck if you want to delete or add to folder.',
    confirmAddToFolders: 'Confirm adding to\nfolder(s)?',
    confirmMoveToFolders: 'Confirm moving to\nfolder(s)?',
    unfavoriteConfirmation: 'Are you sure you want to unfavorite?',
    customGoalFormSubmitted: ['Custom Goal Form', 'Submitted!'],
    deleteDeckConfirmation: 'Are you sure you want to delete this deck?',
    deckMovedToFolder: ['Deck(s) moved', 'into folder(s)!'],
    aiDeckSavedSuccessfully: ['AI Deck', 'saved successfully!'],
    deckSavedToFolder: ['Deck(s) saved', 'into folder(s)!'],
    deleteFolderConfirmation: 'Are you sure you want to delete this folder?',
    decksAlreadyInFolders: ['One or more decks you', 'have selected are already', 'in the selected folder(s)!'],
    // AverageGradeThermometer strings
    averageGrade: 'Average Grade',
    // AverageSpeedTotal strings
    averageTimePerFlashcard: 'Average time per flashcard',
    seconds: 's',
    // BreakdownByDifficultyPie strings
    breakdownByDifficulty: 'Breakdown of Flashcards by Difficulty',
    noDifficultyData: 'No difficulty data available',
    completeSomeFlashcards: 'Complete some flashcards to see your breakdown',
    difficultyLabels: {
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
    },
    // BreakdownOfDecksFlashcards strings
    breakdownOfDecksFlashcards: 'Breakdown of Number of Decks / Flashcards',
    loading: 'Loading...',
    noDataAvailable: 'No data available',
    breakdownDecks: 'Decks',
    breakdownFlashcards: 'Flashcards',
    breakdownCategoryLabels: {
      study: 'Study',
      technical: 'Technical',
      caseStudy: 'Case study',
      behavioral: 'Behavioral',
      brainteasers: 'Brainteasers',
      others: 'Others',
    },
    // GradeChart strings
    gradeChart: 'Grade Chart (%)',
    day: 'Day',
    month: 'Month',
    loadingGradeData: 'Loading grade data...',
    noGradeDataAvailable: 'No grade data available',
    studyOrQuizToSeeProgress: 'Study or quiz flashcards to see your progress',
    // MoreDetailsStats strings
    moreDetails: 'More Details',
    loadingStatistics: 'Loading statistics...',
    moreDetailsDecks: 'Decks',
    moreDetailsFlashcards: 'Flashcards',
    moreDetailsStudy: 'Study',
    moreDetailsInterview: 'Interview',
    accumulatedDecks: 'Accumulated\nDecks',
    decksInLocalStorage: 'Decks in local\nstorage',
    totalDecksQuizzed: 'Total decks\nquizzed',
    accumulatedFlashcards: 'Accumulated\nFlashcards',
    flashcardsInLocalStorage: 'Flashcards in\nlocal storage',
    totalFlashcardsQuizzed: 'Total Flashcards\nquizzed',
    accumulatedStudyDecks: 'Accumulated\nStudy Decks',
    studyDecksInLocalStorage: 'Study decks in\nlocal storage',
    totalStudyDecksQuizzed: 'Total Study\ndecks quizzed',
    accumulatedInterviewDecks: 'Accumulated\nInterview Decks',
    interviewDecksInLocalStorage: 'Interview decks\nin local storage',
    totalInterviewDecksQuizzed: 'Total Interview\ndecks quizzed',
    // ReviewLineGraph strings
    decksFlashcardsReviewed: 'Decks / Flashcards Reviewed',
    loadingReviewData: 'Loading review data...',
    noReviewDataAvailable: 'No review data available yet. Start studying to see your progress!',
    reviewDay: 'Day',
    reviewMonth: 'Month',
    reviewDecks: 'Decks',
    reviewFlashcards: 'Flashcards',
    // SpeedChart strings
    speedChart: 'Speed Chart (average speed per flashcard)',
    loadingSpeedData: 'Loading speed data...',
    noSpeedDataAvailable: 'No speed data available',
    studyOrQuizToSeeSpeedTrends: 'Study or quiz flashcards to see your speed trends',
  },
  Chinese: {
    // AddDeckModal strings
    addFlashcardsToDeck: '添加卡片到卡片组',
    addDeckToFavorites: '添加卡片组到收藏夹',
    addDeckToFolder: '添加卡片组到文件夹',
    addDeck: '添加卡片组',
    genAIForm: 'AI 生成表单',
    fileUpload: '文件上传',
    youtubeLink: 'YouTube 链接',
    manual: '手动添加',
    // InterviewStudyToggle strings
    study: '学习',
    interview: '面试',
    // AIDeckCard strings
    cardTypes: {
      behavioral: '行为面试',
      technical: '技术面试',
      brainteasers: '脑筋急转弯',
      'case study': '案例分析',
      others: '其他',
      study: '学习',
    },
    cards: '张卡片',
    // Card component strings
    progress: '进度',
    completed: '已完成！',
    untitledDeck: '未命名卡片组',
    // AIPromptModal strings
    aiPromptTitle: '试试为你量身定制的AI卡片组！',
    loadingAiDecks: '正在加载AI卡片组...',
    noDeckSuggestions: '哎呀！',
    noDeckSuggestionsSubtitle: '暂无推荐卡片组',
    emptyStateFooter: '随着你的练习',
    emptyStateFooterSubtitle: '我们会生成更多推荐！',
    // FolderCard strings
    decks: '张卡片',
    // FormHeaderIcons strings
    clearAll: '清空',
    // KindsOfQuestions strings
    kindsOfQuestionsTitle: '4. 你想多练习哪些类型的问题？（可多选）',
    questionTypes: {
      recall: '回忆问题',
      comprehension: '理解问题',
      application: '应用问题',
      analysis: '分析问题',
      synthesis: '综合问题',
      evaluation: '评估问题',
      problemSolving: '解决问题',
    },
    // QuestionTextBarWithDropdown strings
    companiesStartingWith: '以',
    selectACompany: '选择一个公司',
    noCompaniesFoundStartingWith: '没有以',
    noCompaniesFound: '没有公司',
    loadingCompanies: '正在加载公司...',
    // TypeOfInterviewQn strings
    typeOfInterviewTitle: '2. 你正在准备哪种面试？（选一）',
    interviewTypes: {
      technical: '技术',
      behavioral: '行为',
      brainteasers: '脑筋急转弯',
      caseStudy: '案例分析',
      others: '其他',
    },
    // ActionButtonsRow strings
    cancel: '取消',
    // BottomTextInputModal strings
    editDeckName: '编辑卡组名称',
    done: '完成',
    // DifficultyToggleRow strings
    difficultyOptions: {
      default: '默认',
      again: '重来',
      hard: '困难',
      good: '良好',
      easy: '简单',
    },
    // HeaderIconButtons strings
    searchPlaceholders: {
      decks: '搜索卡片组',
      folders: '搜索文件夹',
      favorites: '搜索收藏',
      default: '搜索',
    },
    sortOptions: {
      name: '名称',
      dateAdded: '添加日期',
      lastModified: '最近修改',
    },
    // NavBar strings
    navItems: {
      account: '账户',
      decks: '卡片组',
      statistics: '统计',
      awards: '奖励',
      stats: '统计',
    },
    // SlidingMenu strings
    viewFolders: '查看文件夹',
    viewFavorites: '查看收藏',
    // AddViewToggle strings
    addFlashcards: '添加卡片',
    viewFlashcards: '查看卡片',
    // DrawableOptionsRow strings
    clear: '清除',
    // FlippableCard strings
    typeHere: '请在此输入！',
    drawHere: '请在此绘图！',
    pressHoldMic: '按住麦克风按钮录音',
    greatReplay: '太棒了！点击下方按钮播放录音',
    clickToTakeOrUpload: '点击此处拍照或上传图片',
    chooseManual: '请选择上方的手动选项',
    cameraPermissionError: '抱歉，我们需要相机权限才能使用此功能！',
    photoLibraryPermissionError: '抱歉，我们需要相册权限才能使用此功能！',
    imageSelectionError: '选择图片时出错，请重试。',
    photoCaptureError: '拍照时出错，请重试。',
    // CalendarModal strings
    calendarSubtitle: '点击"确定"或"选择日期"应用您的选择。',
    today: '今天',
    thisWeek: '本周',
    thisMonth: '本月',
    all: '全部',
    chooseDate: '选择日期',
    // GenericModal strings
    no: '否',
    yes: '是',
    ok: '确定',
    // TabLayout strings
    deleteDecksConfirmation: '你确定要删除这些卡片组吗？',
    noSelectionMade: '未选择任何内容！',
    noSelectionSubtitle: '如果你想删除或添加到文件夹，请至少选择一个卡片组。',
    confirmAddToFolders: '确认添加到文件夹？',
    confirmMoveToFolders: '确认移动到文件夹？',
    unfavoriteConfirmation: '你确定要取消收藏吗？',
    customGoalFormSubmitted: ['自定义目标表单', '已提交！'],
    deleteDeckConfirmation: '你确定要删除这个卡片组吗？',
    deckMovedToFolder: ['卡片组已移动', '到文件夹！'],
    aiDeckSavedSuccessfully: ['AI卡片组', '保存成功！'],
    deckSavedToFolder: ['卡片组已保存', '到文件夹！'],
    deleteFolderConfirmation: '你确定要删除这个文件夹吗？',
    decksAlreadyInFolders: ['你选择的一个或多个卡片组', '已在所选文件夹中！'],
    // AverageGradeThermometer strings
    averageGrade: '平均分数',
    // AverageSpeedTotal strings
    averageTimePerFlashcard: '平均每张卡片用时',
    seconds: '秒',
    // BreakdownByDifficultyPie strings
    breakdownByDifficulty: '按难度分布的卡片',
    noDifficultyData: '暂无难度数据',
    completeSomeFlashcards: '完成一些卡片以查看分布',
    difficultyLabels: {
      again: '再来',
      hard: '困难',
      good: '良好',
      easy: '简单',
    },
    // BreakdownOfDecksFlashcards strings
    breakdownOfDecksFlashcards: '卡组 / 卡片数量分析',
    loading: '正在加载...',
    noDataAvailable: '暂无数据',
    breakdownDecks: '卡组',
    breakdownFlashcards: '卡片',
    breakdownCategoryLabels: {
      study: '学习',
      technical: '技术',
      caseStudy: '案例分析',
      behavioral: '行为',
      brainteasers: '脑筋急转弯',
      others: '其他',
    },
    // GradeChart strings
    gradeChart: '分数图表 (%)',
    day: '日',
    month: '月',
    loadingGradeData: '正在加载分数数据...',
    noGradeDataAvailable: '暂无分数数据',
    studyOrQuizToSeeProgress: '完成一些卡片以查看分布',
    // MoreDetailsStats strings
    moreDetails: '更多详情',
    loadingStatistics: '正在加载统计...',
    moreDetailsDecks: '卡组',
    moreDetailsFlashcards: '卡片',
    moreDetailsStudy: '学习',
    moreDetailsInterview: '面试',
    accumulatedDecks: '累计\n卡组',
    decksInLocalStorage: '本地\n存储卡组',
    totalDecksQuizzed: '已测\n卡组总数',
    accumulatedFlashcards: '累计\n卡片',
    flashcardsInLocalStorage: '本地\n存储卡片',
    totalFlashcardsQuizzed: '已测\n卡片总数',
    accumulatedStudyDecks: '累计\n学习卡组',
    studyDecksInLocalStorage: '本地\n存储学习卡组',
    totalStudyDecksQuizzed: '已测\n学习卡组总数',
    accumulatedInterviewDecks: '累计\n面试卡组',
    interviewDecksInLocalStorage: '本地\n存储面试卡组',
    totalInterviewDecksQuizzed: '已测\n面试卡组总数',
    // ReviewLineGraph strings
    decksFlashcardsReviewed: '已复习卡组 / 卡片',
    loadingReviewData: '正在加载复习数据...',
    noReviewDataAvailable: '暂无复习数据，开始学习以查看进度！',
    reviewDay: '日',
    reviewMonth: '月',
    reviewDecks: '卡组',
    reviewFlashcards: '卡片',
    // SpeedChart strings
    speedChart: '速度图表（每张卡片的平均速度）',
    loadingSpeedData: '正在加载速度数据...',
    noSpeedDataAvailable: '暂无速度数据',
    studyOrQuizToSeeSpeedTrends: '学习或测验卡片以查看速度趋势',
  },
};
