// Onboarding strings for different languages
export const stringsOnboarding = {
  English: {
    skip: 'Skip',
    next: 'Next',
    back: 'Back',
    welcomeTo: 'Welcome to',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Your learning journey starts here',
    whatAreYouPreppingFor: 'What are you prepping for?',
    studyPrep: 'Study',
    interviewPrep: 'Interview',
    selectLanguage: 'Select Language',
    great: 'Great!',
    justAFewMoreQuestions: 'Just a few more questions to get you started...',
    progress: '1/3',
    whichSubjects: 'Which subject(s) are you prepping for?',
  },
  Chinese: {
    skip: '跳过',
    next: '下一步',
    back: '返回',
    welcomeTo: '欢迎来到',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: '您的学习之旅从这里开始',
    whatAreYouPreppingFor: '您准备什么？',
    studyPrep: '学习',
    interviewPrep: '面试',
    selectLanguage: '选择语言',
    great: '太好了！',
    justAFewMoreQuestions: '再问几个问题来帮你开始...',
    progress: '1/3',
    whichSubjects: '你在准备哪些科目？',
  },
  Malay: {
    skip: 'Langkau',
    next: 'Seterusnya',
    back: 'Kembali',
    welcomeTo: 'Selamat datang ke',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Perjalanan pembelajaran anda bermula di sini',
    whatAreYouPreppingFor: 'Apa yang anda bersedia untuk?',
    studyPrep: 'Belajar',
    interviewPrep: 'Temuduga',
    selectLanguage: 'Pilih Bahasa',
    great: 'Hebat!',
    justAFewMoreQuestions: 'Hanya beberapa soalan lagi untuk memulakan...',
    progress: '1/3',
    whichSubjects: 'Subjek mana yang anda sediakan?',
  },
  Hindi: {
    skip: 'छोड़ें',
    next: 'अगला',
    back: 'वापस',
    welcomeTo: 'आपका स्वागत है',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'आपकी सीखने की यात्रा यहाँ से शुरू होती है',
    whatAreYouPreppingFor: 'आप किसके लिए तैयारी कर रहे हैं?',
    studyPrep: 'अध्ययन',
    interviewPrep: 'साक्षात्कार',
    selectLanguage: 'भाषा चुनें',
    great: 'बहुत बढ़िया!',
    justAFewMoreQuestions: 'आपको शुरू करने के लिए बस कुछ और प्रश्न...',
    progress: '1/3',
    whichSubjects: 'आप किन विषयों की तैयारी कर रहे हैं?',
  },
  French: {
    skip: 'Passer',
    next: 'Suivant',
    back: 'Retour',
    welcomeTo: 'Bienvenue à',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Votre parcours d\'apprentissage commence ici',
    whatAreYouPreppingFor: 'Pour quoi vous préparez-vous?',
    studyPrep: 'Études',
    interviewPrep: 'Entretiens',
    selectLanguage: 'Sélectionner la langue',
    great: 'Parfait !',
    justAFewMoreQuestions: 'Juste quelques questions de plus pour vous aider à commencer...',
    progress: '1/3',
    whichSubjects: 'Pour quelles matières vous préparez-vous ?',
  },
  Japanese: {
    skip: 'スキップ',
    next: '次へ',
    back: '戻る',
    welcomeTo: 'ようこそ',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'あなたの学習の旅がここから始まります',
    whatAreYouPreppingFor: '何の準備をしていますか？',
    studyPrep: '学習',
    interviewPrep: '面接',
    selectLanguage: '言語を選択',
    great: '素晴らしい！',
    justAFewMoreQuestions: '始めるためにあと数問だけ...',
    progress: '1/3',
    whichSubjects: 'どの科目の準備をしていますか？',
  },
  Korean: {
    skip: '건너뛰기',
    next: '다음',
    back: '뒤로',
    welcomeTo: '환영합니다',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: '당신의 학습 여정이 여기서 시작됩니다',
    whatAreYouPreppingFor: '무엇을 준비하고 계신가요?',
    studyPrep: '학습',
    interviewPrep: '면접',
    selectLanguage: '언어 선택',
    great: '훌륭해요!',
    justAFewMoreQuestions: '시작하기 위해 몇 가지 질문만 더...',
    progress: '1/3',
    whichSubjects: '어떤 과목을 준비하고 계신가요?',
  },
  Spanish: {
    skip: 'Omitir',
    next: 'Siguiente',
    back: 'Atrás',
    welcomeTo: 'Bienvenido a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Tu viaje de aprendizaje comienza aquí',
    whatAreYouPreppingFor: '¿Para qué te estás preparando?',
    studyPrep: 'Estudios',
    interviewPrep: 'Entrevistas',
    selectLanguage: 'Seleccionar Idioma',
    great: '¡Genial!',
    justAFewMoreQuestions: 'Solo unas preguntas más para comenzar...',
    progress: '1/3',
    whichSubjects: '¿Para qué materia(s) te estás preparando?',
  },
  German: {
    skip: 'Überspringen',
    next: 'Weiter',
    back: 'Zurück',
    welcomeTo: 'Willkommen bei',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ihre Lernreise beginnt hier',
    whatAreYouPreppingFor: 'Wofür bereiten Sie sich vor?',
    studyPrep: 'Studium',
    interviewPrep: 'Vorstellungsgespräch',
    selectLanguage: 'Sprache auswählen',
    great: 'Großartig!',
    justAFewMoreQuestions: 'Nur noch ein paar Fragen, um loszulegen...',
    progress: '1/3',
    whichSubjects: 'Für welche Fächer bereiten Sie sich vor?',
  },
  Portuguese: {
    skip: 'Pular',
    next: 'Próximo',
    back: 'Voltar',
    welcomeTo: 'Bem-vindo ao',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Sua jornada de aprendizado começa aqui',
    whatAreYouPreppingFor: 'Para o que você está se preparando?',
    studyPrep: 'Estudos',
    interviewPrep: 'Entrevistas',
    selectLanguage: 'Selecionar Idioma',
    great: 'Ótimo!',
    justAFewMoreQuestions: 'Apenas algumas perguntas mais para começar...',
    progress: '1/3',
    whichSubjects: 'Para quais matérias você está se preparando?',
  },
  Italian: {
    skip: 'Salta',
    next: 'Avanti',
    back: 'Indietro',
    welcomeTo: 'Benvenuto a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Il tuo viaggio di apprendimento inizia qui',
    whatAreYouPreppingFor: 'Per cosa ti stai preparando?',
    studyPrep: 'Studi',
    interviewPrep: 'Colloqui',
    selectLanguage: 'Seleziona Lingua',
    great: 'Fantastico!',
    justAFewMoreQuestions: 'Solo alcune domande in più per iniziare...',
    progress: '1/3',
    whichSubjects: 'Per quali materie ti stai preparando?',
  },
  Russian: {
    skip: 'Пропустить',
    next: 'Далее',
    back: 'Назад',
    welcomeTo: 'Добро пожаловать в',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ваше путешествие в обучении начинается здесь',
    whatAreYouPreppingFor: 'К чему вы готовитесь?',
    studyPrep: 'Учеба',
    interviewPrep: 'Собеседование',
    selectLanguage: 'Выберите Язык',
    great: 'Отлично!',
    justAFewMoreQuestions: 'Еще несколько вопросов, чтобы начать...',
    progress: '1/3',
    whichSubjects: 'По каким предметам вы готовитесь?',
  },
  Arabic: {
    skip: 'تخطي',
    next: 'التالي',
    back: 'رجوع',
    welcomeTo: 'مرحباً بك في',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'رحلتك التعليمية تبدأ من هنا',
    whatAreYouPreppingFor: 'لماذا تستعد؟',
    studyPrep: 'الدراسة',
    interviewPrep: 'المقابلة',
    selectLanguage: 'اختر اللغة',
    great: 'رائع!',
    justAFewMoreQuestions: 'بضع أسئلة أخرى للبدء...',
    progress: '1/3',
    whichSubjects: 'أي مادة تحضر لها؟',
  },
  Indonesian: {
    skip: 'Lewati',
    next: 'Selanjutnya',
    back: 'Kembali',
    welcomeTo: 'Selamat datang di',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Perjalanan belajar Anda dimulai di sini',
    whatAreYouPreppingFor: 'Untuk apa Anda mempersiapkan diri?',
    studyPrep: 'Belajar',
    interviewPrep: 'Wawancara',
    selectLanguage: 'Pilih Bahasa',
    great: 'Hebat!',
    justAFewMoreQuestions: 'Beberapa pertanyaan lagi untuk memulai...',
    progress: '1/3',
    whichSubjects: 'Mata pelajaran apa yang Anda persiapkan?',
  },
  Thai: {
    skip: 'ข้าม',
    next: 'ถัดไป',
    back: 'กลับ',
    welcomeTo: 'ยินดีต้อนรับสู่',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'การเดินทางเรียนรู้ของคุณเริ่มต้นที่นี่',
    whatAreYouPreppingFor: 'คุณกำลังเตรียมตัวสำหรับอะไร?',
    studyPrep: 'การเรียน',
    interviewPrep: 'การสัมภาษณ์',
    selectLanguage: 'เลือกภาษา',
    great: 'เยี่ยม!',
    justAFewMoreQuestions: 'คำถามอีกไม่กี่ข้อเพื่อเริ่มต้น...',
    progress: '1/3',
    whichSubjects: 'คุณกำลังเตรียมตัวสำหรับวิชาใด?',
  },
  Vietnamese: {
    skip: 'Bỏ qua',
    next: 'Tiếp theo',
    back: 'Quay lại',
    welcomeTo: 'Chào mừng đến với',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Hành trình học tập của bạn bắt đầu từ đây',
    whatAreYouPreppingFor: 'Bạn đang chuẩn bị cho gì?',
    studyPrep: 'Học tập',
    interviewPrep: 'Phỏng vấn',
    selectLanguage: 'Chọn Ngôn ngữ',
    great: 'Tuyệt vời!',
    justAFewMoreQuestions: 'Chỉ còn một vài câu hỏi nữa để bắt đầu...',
    progress: '1/3',
    whichSubjects: 'Bạn đang chuẩn bị cho môn học nào?',
  },
  Turkish: {
    skip: 'Atla',
    next: 'İleri',
    back: 'Geri',
    welcomeTo: 'Hoş geldiniz',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Öğrenme yolculuğunuz burada başlıyor',
    whatAreYouPreppingFor: 'Neye hazırlanıyorsunuz?',
    studyPrep: 'Çalışma',
    interviewPrep: 'Mülakat',
    selectLanguage: 'Dil Seçin',
    great: 'Harika!',
    justAFewMoreQuestions: 'Başlamak için sadece birkaç soru daha...',
    progress: '1/3',
    whichSubjects: 'Hangi konulara hazırlanıyorsunuz?',
  },
  Dutch: {
    skip: 'Overslaan',
    next: 'Volgende',
    back: 'Terug',
    welcomeTo: 'Welkom bij',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Uw leerreis begint hier',
    whatAreYouPreppingFor: 'Waar bereidt u zich op voor?',
    studyPrep: 'Studie',
    interviewPrep: 'Sollicitatie',
    selectLanguage: 'Selecteer Taal',
    great: 'Geweldig!',
    justAFewMoreQuestions: 'Nog een paar vragen om te beginnen...',
    progress: '1/3',
    whichSubjects: 'Voor welke vakken bereid je je voor?',
  },
  Polish: {
    skip: 'Pomiń',
    next: 'Dalej',
    back: 'Wstecz',
    welcomeTo: 'Witamy w',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Twoja podróż edukacyjna zaczyna się tutaj',
    whatAreYouPreppingFor: 'Na co się przygotowujesz?',
    studyPrep: 'Studia',
    interviewPrep: 'Rozmowa',
    selectLanguage: 'Wybierz Język',
    great: 'Świetnie!',
    justAFewMoreQuestions: 'Jeszcze kilka pytań, aby zacząć...',
    progress: '1/3',
    whichSubjects: 'Do jakich przedmiotów się przygotowujesz?',
  },
  Swedish: {
    skip: 'Hoppa över',
    next: 'Nästa',
    back: 'Tillbaka',
    welcomeTo: 'Välkommen till',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din inlärningsresa börjar här',
    whatAreYouPreppingFor: 'För vad förbereder du dig?',
    studyPrep: 'Studier',
    interviewPrep: 'Intervju',
    selectLanguage: 'Välj Språk',
    great: 'Fantastiskt!',
    justAFewMoreQuestions: 'Bara några frågor till för att komma igång...',
    progress: '1/3',
    whichSubjects: 'Vilka ämnen förbereder du dig för?',
  },
  Czech: {
    skip: 'Přeskočit',
    next: 'Další',
    back: 'Zpět',
    welcomeTo: 'Vítejte v',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Vaše vzdělávací cesta začíná zde',
    whatAreYouPreppingFor: 'Na co se připravujete?',
    studyPrep: 'Studium',
    interviewPrep: 'Rozhovor',
    selectLanguage: 'Vyberte Jazyk',
    great: 'Skvělé!',
    justAFewMoreQuestions: 'Ještě několik otázek k začátku...',
    progress: '1/3',
    whichSubjects: 'Pro jaké předměty se připravujete?',
  },
  Greek: {
    skip: 'Παράλειψη',
    next: 'Επόμενο',
    back: 'Πίσω',
    welcomeTo: 'Καλώς ήρθατε στο',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Το ταξίδι μάθησής σας ξεκινά εδώ',
    whatAreYouPreppingFor: 'Για τι προετοιμάζεστε;',
    studyPrep: 'Σπουδές',
    interviewPrep: 'Συνέντευξη',
    selectLanguage: 'Επιλέξτε Γλώσσα',
    great: 'Τέλεια!',
    justAFewMoreQuestions: 'Μόνο λίγες ακόμα ερωτήσεις για να ξεκινήσετε...',
    progress: '1/3',
    whichSubjects: 'Για ποια μαθήματα προετοιμάζεστε;',
  },
  Hebrew: {
    skip: 'דלג',
    next: 'הבא',
    back: 'חזור',
    welcomeTo: 'ברוכים הבאים ל',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'מסע הלמידה שלכם מתחיל כאן',
    whatAreYouPreppingFor: 'למה אתם מתכוננים?',
    studyPrep: 'לימודים',
    interviewPrep: 'ראיון',
    selectLanguage: 'בחר שפה',
    great: 'נהדר!',
    justAFewMoreQuestions: 'רק עוד כמה שאלות כדי להתחיל...',
    progress: '1/3',
    whichSubjects: 'איזה נושאים אתם מתכוננים?',
  },
  Tagalog: {
    skip: 'Laktawan',
    next: 'Susunod',
    back: 'Balik',
    welcomeTo: 'Maligayang pagdating sa',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ang inyong pag-aaral na paglalakbay ay nagsisimula dito',
    whatAreYouPreppingFor: 'Para saan kayo naghahanda?',
    studyPrep: 'Pag-aaral',
    interviewPrep: 'Panayam',
    selectLanguage: 'Pumili ng Wika',
    great: 'Mahusay!',
    justAFewMoreQuestions: 'Ilang tanong pa lang para makapagsimula...',
    progress: '1/3',
    whichSubjects: 'Para saang mga paksa kayo naghahanda?',
  },
  Tamil: {
    skip: 'தவிர்க்க',
    next: 'அடுத்து',
    back: 'திரும்பு',
    welcomeTo: 'வரவேற்கிறோம்',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'உங்கள் கற்றல் பயணம் இங்கே தொடங்குகிறது',
    whatAreYouPreppingFor: 'நீங்கள் எதற்காக தயாராகிறீர்கள்?',
    studyPrep: 'படிப்பு',
    interviewPrep: 'நேர்காணல்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    great: 'அருமை!',
    justAFewMoreQuestions: 'தொடங்க சில கேள்விகள் மட்டும்...',
    progress: '1/3',
    whichSubjects: 'நீங்கள் எந்த பாடங்களுக்கு தயாராகிறீர்கள்?',
  },
  Bengali: {
    skip: 'এড়িয়ে যান',
    next: 'পরবর্তী',
    back: 'ফিরে যান',
    welcomeTo: 'স্বাগতম',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'আপনার শেখার যাত্রা এখান থেকে শুরু হয়',
    whatAreYouPreppingFor: 'আপনি কোনটির জন্য প্রস্তুত হচ্ছেন?',
    studyPrep: 'পড়াশোনা',
    interviewPrep: 'সাক্ষাত্কার',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    great: 'দারুণ!',
    justAFewMoreQuestions: 'শুরু করার জন্য আরও কয়েকটি প্রশ্ন...',
    progress: '1/3',
    whichSubjects: 'আপনি কোন বিষয়ের জন্য প্রস্তুত হচ্ছেন?',
  },
  Ukrainian: {
    skip: 'Пропустити',
    next: 'Далі',
    back: 'Назад',
    welcomeTo: 'Ласкаво просимо до',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ваша подорож навчання починається тут',
    whatAreYouPreppingFor: 'До чого ви готуєтеся?',
    studyPrep: 'Навчання',
    interviewPrep: 'Співбесіда',
    selectLanguage: 'Оберіть Мову',
    great: 'Чудово!',
    justAFewMoreQuestions: 'Ще кілька питань для початку...',
    progress: '1/3',
    whichSubjects: 'З яких предметів ви готуєтеся?',
  },
  Romanian: {
    skip: 'Omite',
    next: 'Următorul',
    back: 'Înapoi',
    welcomeTo: 'Bun venit la',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Călătoria ta de învățare începe aici',
    whatAreYouPreppingFor: 'Pentru ce te pregătești?',
    studyPrep: 'Studii',
    interviewPrep: 'Interviu',
    selectLanguage: 'Selectează Limba',
    great: 'Minunat!',
    justAFewMoreQuestions: 'Doar câteva întrebări în plus pentru a începe...',
    progress: '1/3',
    whichSubjects: 'Pentru ce materii te pregătești?',
  },
  Hungarian: {
    skip: 'Kihagyás',
    next: 'Következő',
    back: 'Vissza',
    welcomeTo: 'Üdvözöljük a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'A tanulási utazásod itt kezdődik',
    whatAreYouPreppingFor: 'Mire készülsz fel?',
    studyPrep: 'Tanulmány',
    interviewPrep: 'Interjú',
    selectLanguage: 'Válassz Nyelvet',
    great: 'Nagyszerű!',
    justAFewMoreQuestions: 'Csak néhány kérdés még, hogy elkezdhesd...',
    progress: '1/3',
    whichSubjects: 'Milyen tantárgyakhoz készülsz fel?',
  },
  Farsi: {
    skip: 'رد کردن',
    next: 'بعدی',
    back: 'بازگشت',
    welcomeTo: 'خوش آمدید به',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'سفر یادگیری شما از اینجا آغاز می‌شود',
    whatAreYouPreppingFor: 'برای چه چیزی آماده می‌شوید؟',
    studyPrep: 'تحصیل',
    interviewPrep: 'مصاحبه',
    selectLanguage: 'انتخاب زبان',
    great: 'عالی!',
    justAFewMoreQuestions: 'فقط چند سؤال دیگر برای شروع...',
    progress: '1/3',
    whichSubjects: 'برای چه موضوعاتی آماده می‌شوید؟',
  },
  Swahili: {
    skip: 'Ruka',
    next: 'Ifuatayo',
    back: 'Rudi',
    welcomeTo: 'Karibu',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Safari yako ya kujifunza inaanza hapa',
    whatAreYouPreppingFor: 'Unajiandaa kwa nini?',
    studyPrep: 'Masomo',
    interviewPrep: 'Mahojiano',
    selectLanguage: 'Chagua Lugha',
    great: 'Vizuri!',
    justAFewMoreQuestions: 'Maswali machache tu ya kuanza...',
    progress: '1/3',
    whichSubjects: 'Unaandaa masomo gani?',
  },
  Afrikaans: {
    skip: 'Slaan Oor',
    next: 'Volgende',
    back: 'Terug',
    welcomeTo: 'Welkom by',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Jou leerreis begin hier',
    whatAreYouPreppingFor: 'Waarvoor berei jy jou voor?',
    studyPrep: 'Studie',
    interviewPrep: 'Onderhoud',
    selectLanguage: 'Kies Taal',
    great: 'Geweldig!',
    justAFewMoreQuestions: 'Net nog \'n paar vrae om te begin...',
    progress: '1/3',
    whichSubjects: 'Vir watter vakke berei jy jou voor?',
  },
  Finnish: {
    skip: 'Ohita',
    next: 'Seuraava',
    back: 'Takaisin',
    welcomeTo: 'Tervetuloa',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Oppimismatkasi alkaa täältä',
    whatAreYouPreppingFor: 'Mihin valmistaudut?',
    studyPrep: 'Opiskelu',
    interviewPrep: 'Haastattelu',
    selectLanguage: 'Valitse Kieli',
    great: 'Hienoa!',
    justAFewMoreQuestions: 'Vain muutama kysymys lisää aloittamiseen...',
    progress: '1/3',
    whichSubjects: 'Mihin aineisiin valmistaudut?',
  },
  Norwegian: {
    skip: 'Hopp Over',
    next: 'Neste',
    back: 'Tilbake',
    welcomeTo: 'Velkommen til',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din læringsreise begynner her',
    whatAreYouPreppingFor: 'Hva forbereder du deg på?',
    studyPrep: 'Studie',
    interviewPrep: 'Intervju',
    selectLanguage: 'Velg Språk',
    great: 'Flott!',
    justAFewMoreQuestions: 'Bare noen få spørsmål til for å komme i gang...',
    progress: '1/3',
    whichSubjects: 'Hvilke fag forbereder du deg på?',
  },
  Danish: {
    skip: 'Spring Over',
    next: 'Næste',
    back: 'Tilbage',
    welcomeTo: 'Velkommen til',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din læringsrejse begynder her',
    whatAreYouPreppingFor: 'Hvad forbereder du dig på?',
    studyPrep: 'Studie',
    interviewPrep: 'Interview',
    selectLanguage: 'Vælg Sprog',
    great: 'Fantastisk!',
    justAFewMoreQuestions: 'Bare et par spørgsmål mere for at komme i gang...',
    progress: '1/3',
    whichSubjects: 'Hvilke fag forbereder du dig på?',
  },
};

export const getTranslatedText = (language: string, key: string): string => {
  const lang = stringsOnboarding[language as keyof typeof stringsOnboarding];
  if (!lang) {
    return stringsOnboarding.English[key as keyof typeof stringsOnboarding.English];
  }
  return lang[key as keyof typeof lang] || stringsOnboarding.English[key as keyof typeof stringsOnboarding.English];
};
