// Onboarding strings for different languages
export const stringsOnboarding = {
  English: {
    skip: 'Skip',
    next: 'Next',
    back: 'Back',
    welcomeTo: 'Welcome to',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Your learning journey starts here',
    whatAreYouPreppingFor: 'What are you prepping for?',
    studyPrep: 'Study',
    interviewPrep: 'Interview',
    selectLanguage: 'Select Language',
  },
  Chinese: {
    skip: '跳过',
    next: '下一步',
    back: '返回',
    welcomeTo: '欢迎来到',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: '您的学习之旅从这里开始',
    whatAreYouPreppingFor: '您准备什么？',
    studyPrep: '学习',
    interviewPrep: '面试',
    selectLanguage: '选择语言',
  },
  Malay: {
    skip: 'Langkau',
    next: 'Seterusnya',
    back: 'Kembali',
    welcomeTo: 'Selamat datang ke',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Perjalanan pembelajaran anda bermula di sini',
    whatAreYouPreppingFor: 'Apa yang anda bersedia untuk?',
    studyPrep: 'Belajar',
    interviewPrep: 'Temuduga',
    selectLanguage: 'Pilih Bahasa',
  },
  Hindi: {
    skip: 'छोड़ें',
    next: 'अगला',
    back: 'वापस',
    welcomeTo: 'आपका स्वागत है',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'आपकी सीखने की यात्रा यहाँ से शुरू होती है',
    whatAreYouPreppingFor: 'आप किसके लिए तैयारी कर रहे हैं?',
    studyPrep: 'अध्ययन',
    interviewPrep: 'साक्षात्कार',
    selectLanguage: 'भाषा चुनें',
  },
  French: {
    skip: 'Passer',
    next: 'Suivant',
    back: 'Retour',
    welcomeTo: 'Bienvenue à',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Votre parcours d\'apprentissage commence ici',
    whatAreYouPreppingFor: 'Pour quoi vous préparez-vous?',
    studyPrep: 'Études',
    interviewPrep: 'Entretiens',
    selectLanguage: 'Sélectionner la langue',
  },
  Japanese: {
    skip: 'スキップ',
    next: '次へ',
    back: '戻る',
    welcomeTo: 'ようこそ',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'あなたの学習の旅がここから始まります',
    whatAreYouPreppingFor: '何の準備をしていますか？',
    studyPrep: '学習',
    interviewPrep: '面接',
    selectLanguage: '言語を選択',
  },
  Korean: {
    skip: '건너뛰기',
    next: '다음',
    back: '뒤로',
    welcomeTo: '환영합니다',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: '당신의 학습 여정이 여기서 시작됩니다',
    whatAreYouPreppingFor: '무엇을 준비하고 계신가요?',
    studyPrep: '학습',
    interviewPrep: '면접',
    selectLanguage: '언어 선택',
  },
  Spanish: {
    skip: 'Omitir',
    next: 'Siguiente',
    back: 'Atrás',
    welcomeTo: 'Bienvenido a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Tu viaje de aprendizaje comienza aquí',
    whatAreYouPreppingFor: '¿Para qué te estás preparando?',
    studyPrep: 'Estudios',
    interviewPrep: 'Entrevistas',
    selectLanguage: 'Seleccionar Idioma',
  },
  German: {
    skip: 'Überspringen',
    next: 'Weiter',
    back: 'Zurück',
    welcomeTo: 'Willkommen bei',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ihre Lernreise beginnt hier',
    whatAreYouPreppingFor: 'Wofür bereiten Sie sich vor?',
    studyPrep: 'Studium',
    interviewPrep: 'Vorstellungsgespräch',
    selectLanguage: 'Sprache auswählen',
  },
  Portuguese: {
    skip: 'Pular',
    next: 'Próximo',
    back: 'Voltar',
    welcomeTo: 'Bem-vindo ao',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Sua jornada de aprendizado começa aqui',
    whatAreYouPreppingFor: 'Para o que você está se preparando?',
    studyPrep: 'Estudos',
    interviewPrep: 'Entrevistas',
    selectLanguage: 'Selecionar Idioma',
  },
  Italian: {
    skip: 'Salta',
    next: 'Avanti',
    back: 'Indietro',
    welcomeTo: 'Benvenuto a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Il tuo viaggio di apprendimento inizia qui',
    whatAreYouPreppingFor: 'Per cosa ti stai preparando?',
    studyPrep: 'Studi',
    interviewPrep: 'Colloqui',
    selectLanguage: 'Seleziona Lingua',
  },
  Russian: {
    skip: 'Пропустить',
    next: 'Далее',
    back: 'Назад',
    welcomeTo: 'Добро пожаловать в',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ваше путешествие в обучении начинается здесь',
    whatAreYouPreppingFor: 'К чему вы готовитесь?',
    studyPrep: 'Учеба',
    interviewPrep: 'Собеседование',
    selectLanguage: 'Выберите Язык',
  },
  Arabic: {
    skip: 'تخطي',
    next: 'التالي',
    back: 'رجوع',
    welcomeTo: 'مرحباً بك في',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'رحلتك التعليمية تبدأ من هنا',
    whatAreYouPreppingFor: 'لماذا تستعد؟',
    studyPrep: 'الدراسة',
    interviewPrep: 'المقابلة',
    selectLanguage: 'اختر اللغة',
  },
  Indonesian: {
    skip: 'Lewati',
    next: 'Selanjutnya',
    back: 'Kembali',
    welcomeTo: 'Selamat datang di',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Perjalanan belajar Anda dimulai di sini',
    whatAreYouPreppingFor: 'Untuk apa Anda mempersiapkan diri?',
    studyPrep: 'Belajar',
    interviewPrep: 'Wawancara',
    selectLanguage: 'Pilih Bahasa',
  },
  Thai: {
    skip: 'ข้าม',
    next: 'ถัดไป',
    back: 'กลับ',
    welcomeTo: 'ยินดีต้อนรับสู่',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'การเดินทางเรียนรู้ของคุณเริ่มต้นที่นี่',
    whatAreYouPreppingFor: 'คุณกำลังเตรียมตัวสำหรับอะไร?',
    studyPrep: 'การเรียน',
    interviewPrep: 'การสัมภาษณ์',
    selectLanguage: 'เลือกภาษา',
  },
  Vietnamese: {
    skip: 'Bỏ qua',
    next: 'Tiếp theo',
    back: 'Quay lại',
    welcomeTo: 'Chào mừng đến với',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Hành trình học tập của bạn bắt đầu từ đây',
    whatAreYouPreppingFor: 'Bạn đang chuẩn bị cho gì?',
    studyPrep: 'Học tập',
    interviewPrep: 'Phỏng vấn',
    selectLanguage: 'Chọn Ngôn ngữ',
  },
  Turkish: {
    skip: 'Atla',
    next: 'İleri',
    back: 'Geri',
    welcomeTo: 'Hoş geldiniz',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Öğrenme yolculuğunuz burada başlıyor',
    whatAreYouPreppingFor: 'Neye hazırlanıyorsunuz?',
    studyPrep: 'Çalışma',
    interviewPrep: 'Mülakat',
    selectLanguage: 'Dil Seçin',
  },
  Dutch: {
    skip: 'Overslaan',
    next: 'Volgende',
    back: 'Terug',
    welcomeTo: 'Welkom bij',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Uw leerreis begint hier',
    whatAreYouPreppingFor: 'Waar bereidt u zich op voor?',
    studyPrep: 'Studie',
    interviewPrep: 'Sollicitatie',
    selectLanguage: 'Selecteer Taal',
  },
  Polish: {
    skip: 'Pomiń',
    next: 'Dalej',
    back: 'Wstecz',
    welcomeTo: 'Witamy w',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Twoja podróż edukacyjna zaczyna się tutaj',
    whatAreYouPreppingFor: 'Na co się przygotowujesz?',
    studyPrep: 'Studia',
    interviewPrep: 'Rozmowa',
    selectLanguage: 'Wybierz Język',
  },
  Swedish: {
    skip: 'Hoppa över',
    next: 'Nästa',
    back: 'Tillbaka',
    welcomeTo: 'Välkommen till',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din inlärningsresa börjar här',
    whatAreYouPreppingFor: 'För vad förbereder du dig?',
    studyPrep: 'Studier',
    interviewPrep: 'Intervju',
    selectLanguage: 'Välj Språk',
  },
  Czech: {
    skip: 'Přeskočit',
    next: 'Další',
    back: 'Zpět',
    welcomeTo: 'Vítejte v',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Vaše vzdělávací cesta začíná zde',
    whatAreYouPreppingFor: 'Na co se připravujete?',
    studyPrep: 'Studium',
    interviewPrep: 'Rozhovor',
    selectLanguage: 'Vyberte Jazyk',
  },
  Greek: {
    skip: 'Παράλειψη',
    next: 'Επόμενο',
    back: 'Πίσω',
    welcomeTo: 'Καλώς ήρθατε στο',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Το ταξίδι μάθησής σας ξεκινά εδώ',
    whatAreYouPreppingFor: 'Για τι προετοιμάζεστε;',
    studyPrep: 'Σπουδές',
    interviewPrep: 'Συνέντευξη',
    selectLanguage: 'Επιλέξτε Γλώσσα',
  },
  Hebrew: {
    skip: 'דלג',
    next: 'הבא',
    back: 'חזור',
    welcomeTo: 'ברוכים הבאים ל',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'מסע הלמידה שלכם מתחיל כאן',
    whatAreYouPreppingFor: 'למה אתם מתכוננים?',
    studyPrep: 'לימודים',
    interviewPrep: 'ראיון',
    selectLanguage: 'בחר שפה',
  },
  Tagalog: {
    skip: 'Laktawan',
    next: 'Susunod',
    back: 'Balik',
    welcomeTo: 'Maligayang pagdating sa',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ang inyong pag-aaral na paglalakbay ay nagsisimula dito',
    whatAreYouPreppingFor: 'Para saan kayo naghahanda?',
    studyPrep: 'Pag-aaral',
    interviewPrep: 'Panayam',
    selectLanguage: 'Pumili ng Wika',
  },
  Tamil: {
    skip: 'தவிர்க்க',
    next: 'அடுத்து',
    back: 'திரும்பு',
    welcomeTo: 'வரவேற்கிறோம்',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'உங்கள் கற்றல் பயணம் இங்கே தொடங்குகிறது',
    whatAreYouPreppingFor: 'நீங்கள் எதற்காக தயாராகிறீர்கள்?',
    studyPrep: 'படிப்பு',
    interviewPrep: 'நேர்காணல்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
  },
  Bengali: {
    skip: 'এড়িয়ে যান',
    next: 'পরবর্তী',
    back: 'ফিরে যান',
    welcomeTo: 'স্বাগতম',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'আপনার শেখার যাত্রা এখান থেকে শুরু হয়',
    whatAreYouPreppingFor: 'আপনি কোনটির জন্য প্রস্তুত হচ্ছেন?',
    studyPrep: 'পড়াশোনা',
    interviewPrep: 'সাক্ষাত্কার',
    selectLanguage: 'ভাষা নির্বাচন করুন',
  },
  Ukrainian: {
    skip: 'Пропустити',
    next: 'Далі',
    back: 'Назад',
    welcomeTo: 'Ласкаво просимо до',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ваша подорож навчання починається тут',
    whatAreYouPreppingFor: 'До чого ви готуєтеся?',
    studyPrep: 'Навчання',
    interviewPrep: 'Співбесіда',
    selectLanguage: 'Оберіть Мову',
  },
  Romanian: {
    skip: 'Omite',
    next: 'Următorul',
    back: 'Înapoi',
    welcomeTo: 'Bun venit la',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Călătoria ta de învățare începe aici',
    whatAreYouPreppingFor: 'Pentru ce te pregătești?',
    studyPrep: 'Studii',
    interviewPrep: 'Interviu',
    selectLanguage: 'Selectează Limba',
  },
  Hungarian: {
    skip: 'Kihagyás',
    next: 'Következő',
    back: 'Vissza',
    welcomeTo: 'Üdvözöljük a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'A tanulási utazásod itt kezdődik',
    whatAreYouPreppingFor: 'Mire készülsz fel?',
    studyPrep: 'Tanulmány',
    interviewPrep: 'Interjú',
    selectLanguage: 'Válassz Nyelvet',
  },
  Farsi: {
    skip: 'رد کردن',
    next: 'بعدی',
    back: 'بازگشت',
    welcomeTo: 'خوش آمدید به',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'سفر یادگیری شما از اینجا آغاز می‌شود',
    whatAreYouPreppingFor: 'برای چه چیزی آماده می‌شوید؟',
    studyPrep: 'تحصیل',
    interviewPrep: 'مصاحبه',
    selectLanguage: 'انتخاب زبان',
  },
  Swahili: {
    skip: 'Ruka',
    next: 'Ifuatayo',
    back: 'Rudi',
    welcomeTo: 'Karibu',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Safari yako ya kujifunza inaanza hapa',
    whatAreYouPreppingFor: 'Unajiandaa kwa nini?',
    studyPrep: 'Masomo',
    interviewPrep: 'Mahojiano',
    selectLanguage: 'Chagua Lugha',
  },
  Afrikaans: {
    skip: 'Slaan Oor',
    next: 'Volgende',
    back: 'Terug',
    welcomeTo: 'Welkom by',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Jou leerreis begin hier',
    whatAreYouPreppingFor: 'Waarvoor berei jy jou voor?',
    studyPrep: 'Studie',
    interviewPrep: 'Onderhoud',
    selectLanguage: 'Kies Taal',
  },
  Finnish: {
    skip: 'Ohita',
    next: 'Seuraava',
    back: 'Takaisin',
    welcomeTo: 'Tervetuloa',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Oppimismatkasi alkaa täältä',
    whatAreYouPreppingFor: 'Mihin valmistaudut?',
    studyPrep: 'Opiskelu',
    interviewPrep: 'Haastattelu',
    selectLanguage: 'Valitse Kieli',
  },
  Norwegian: {
    skip: 'Hopp Over',
    next: 'Neste',
    back: 'Tilbake',
    welcomeTo: 'Velkommen til',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din læringsreise begynner her',
    whatAreYouPreppingFor: 'Hva forbereder du deg på?',
    studyPrep: 'Studie',
    interviewPrep: 'Intervju',
    selectLanguage: 'Velg Språk',
  },
  Danish: {
    skip: 'Spring Over',
    next: 'Næste',
    back: 'Tilbage',
    welcomeTo: 'Velkommen til',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din læringsrejse begynder her',
    whatAreYouPreppingFor: 'Hvad forbereder du dig på?',
    studyPrep: 'Studie',
    interviewPrep: 'Interview',
    selectLanguage: 'Vælg Sprog',
  },
};

export const getTranslatedText = (language: string, key: string): string => {
  const lang = stringsOnboarding[language as keyof typeof stringsOnboarding];
  if (!lang) {
    return stringsOnboarding.English[key as keyof typeof stringsOnboarding.English];
  }
  return lang[key as keyof typeof lang] || stringsOnboarding.English[key as keyof typeof stringsOnboarding.English];
};
