// Onboarding strings for different languages
export const stringsOnboarding = {
  English: {
    skip: 'Skip',
    next: 'Next',
    back: 'Back',
    welcomeTo: 'Welcome to',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Your learning journey starts here',
    whatAreYouPreppingFor: 'What are you prepping for?',
    studyPrep: 'Study',
    interviewPrep: 'Interview',
    selectLanguage: 'Select Language',
    great: 'Great!',
    justAFewMoreQuestions: 'Just a few more questions to get you started...',
    progress: '1/3',
    whichSubjects: 'Which subject(s) are you prepping for?',
    // Study subjects
    history: 'History',
    physics: 'Physics',
    chemistry: 'Chemistry',
    biology: 'Biology',
    geography: 'Geography',
    math: 'Math',
    medicine: 'Medicine',
    law: 'Law',
    finance: 'Finance',
    computing: 'Computing',
    // Interview subjects
    softwareEngineering: 'Software Engineering',
    investmentBanking: 'Investment Banking',
    medicalResidency: 'Medical Residency',
    quantitativeResearcher: 'Quantitative Researcher',
    managementConsulting: 'Management Consulting',
    criminalLawyer: 'Criminal Lawyer',
    electricalEngineer: 'Electrical Engineer',
    productManager: 'Product Manager',
  },
  Chinese: {
    skip: '跳过',
    next: '下一步',
    back: '返回',
    welcomeTo: '欢迎来到',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: '您的学习之旅从这里开始',
    whatAreYouPreppingFor: '您准备什么？',
    studyPrep: '学习',
    interviewPrep: '面试',
    selectLanguage: '选择语言',
    great: '太好了！',
    justAFewMoreQuestions: '再问几个问题来帮你开始...',
    progress: '1/3',
    whichSubjects: '你在准备哪些科目？',
    // Study subjects
    history: '历史',
    physics: '物理',
    chemistry: '化学',
    biology: '生物',
    geography: '地理',
    math: '数学',
    medicine: '医学',
    law: '法律',
    finance: '金融',
    computing: '计算机',
    // Interview subjects
    softwareEngineering: '软件工程',
    investmentBanking: '投资银行',
    medicalResidency: '医学住院医师',
    quantitativeResearcher: '量化研究员',
    managementConsulting: '管理咨询',
    criminalLawyer: '刑事律师',
    electricalEngineer: '电气工程师',
    productManager: '产品经理',
  },
  Malay: {
    skip: 'Langkau',
    next: 'Seterusnya',
    back: 'Kembali',
    welcomeTo: 'Selamat datang ke',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Perjalanan pembelajaran anda bermula di sini',
    whatAreYouPreppingFor: 'Apa yang anda bersedia untuk?',
    studyPrep: 'Belajar',
    interviewPrep: 'Temuduga',
    selectLanguage: 'Pilih Bahasa',
    great: 'Hebat!',
    justAFewMoreQuestions: 'Hanya beberapa soalan lagi untuk memulakan...',
    progress: '1/3',
    whichSubjects: 'Subjek mana yang anda sediakan?',
    // Study subjects
    history: 'Sejarah',
    physics: 'Fizik',
    chemistry: 'Kimia',
    biology: 'Biologi',
    geography: 'Geografi',
    math: 'Matematik',
    medicine: 'Perubatan',
    law: 'Undang-undang',
    finance: 'Kewangan',
    computing: 'Pengkomputeran',
    // Interview subjects
    softwareEngineering: 'Kejuruteraan Perisian',
    investmentBanking: 'Bank Pelaburan',
    medicalResidency: 'Residensi Perubatan',
    quantitativeResearcher: 'Penyelidik Kuantitatif',
    managementConsulting: 'Perundingan Pengurusan',
    criminalLawyer: 'Peguam Jenayah',
    electricalEngineer: 'Jurutera Elektrik',
    productManager: 'Pengurus Produk',
  },
  Hindi: {
    skip: 'छोड़ें',
    next: 'अगला',
    back: 'वापस',
    welcomeTo: 'आपका स्वागत है',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'आपकी सीखने की यात्रा यहाँ से शुरू होती है',
    whatAreYouPreppingFor: 'आप किसके लिए तैयारी कर रहे हैं?',
    studyPrep: 'अध्ययन',
    interviewPrep: 'साक्षात्कार',
    selectLanguage: 'भाषा चुनें',
    great: 'बहुत बढ़िया!',
    justAFewMoreQuestions: 'आपको शुरू करने के लिए बस कुछ और प्रश्न...',
    progress: '1/3',
    whichSubjects: 'आप किन विषयों की तैयारी कर रहे हैं?',
    // Study subjects
    history: 'इतिहास',
    physics: 'भौतिकी',
    chemistry: 'रसायन विज्ञान',
    biology: 'जीव विज्ञान',
    geography: 'भूगोल',
    math: 'गणित',
    medicine: 'चिकित्सा',
    law: 'कानून',
    finance: 'वित्त',
    computing: 'कंप्यूटिंग',
    // Interview subjects
    softwareEngineering: 'सॉफ्टवेयर इंजीनियरिंग',
    investmentBanking: 'निवेश बैंकिंग',
    medicalResidency: 'चिकित्सा निवास',
    quantitativeResearcher: 'मात्रात्मक शोधकर्ता',
    managementConsulting: 'प्रबंधन सलाहकार',
    criminalLawyer: 'आपराधिक वकील',
    electricalEngineer: 'इलेक्ट्रिकल इंजीनियर',
    productManager: 'उत्पाद प्रबंधक',
  },
  French: {
    skip: 'Passer',
    next: 'Suivant',
    back: 'Retour',
    welcomeTo: 'Bienvenue à',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Votre parcours d\'apprentissage commence ici',
    whatAreYouPreppingFor: 'Pour quoi vous préparez-vous?',
    studyPrep: 'Études',
    interviewPrep: 'Entretiens',
    selectLanguage: 'Sélectionner la langue',
    great: 'Parfait !',
    justAFewMoreQuestions: 'Juste quelques questions de plus pour vous aider à commencer...',
    progress: '1/3',
    whichSubjects: 'Pour quelles matières vous préparez-vous ?',
    // Study subjects
    history: 'Histoire',
    physics: 'Physique',
    chemistry: 'Chimie',
    biology: 'Biologie',
    geography: 'Géographie',
    math: 'Mathématiques',
    medicine: 'Médecine',
    law: 'Droit',
    finance: 'Finance',
    computing: 'Informatique',
    // Interview subjects
    softwareEngineering: 'Génie Logiciel',
    investmentBanking: 'Banque d\'Investissement',
    medicalResidency: 'Résidence Médicale',
    quantitativeResearcher: 'Chercheur Quantitatif',
    managementConsulting: 'Conseil en Gestion',
    criminalLawyer: 'Avocat Pénal',
    electricalEngineer: 'Ingénieur Électricien',
    productManager: 'Gestionnaire de Produit',
  },
  Japanese: {
    skip: 'スキップ',
    next: '次へ',
    back: '戻る',
    welcomeTo: 'ようこそ',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'あなたの学習の旅がここから始まります',
    whatAreYouPreppingFor: '何の準備をしていますか？',
    studyPrep: '学習',
    interviewPrep: '面接',
    selectLanguage: '言語を選択',
    great: '素晴らしい！',
    justAFewMoreQuestions: '始めるためにあと数問だけ...',
    progress: '1/3',
    whichSubjects: 'どの科目の準備をしていますか？',
    // Study subjects
    history: '歴史',
    physics: '物理学',
    chemistry: '化学',
    biology: '生物学',
    geography: '地理学',
    math: '数学',
    medicine: '医学',
    law: '法学',
    finance: '金融',
    computing: 'コンピューティング',
    // Interview subjects
    softwareEngineering: 'ソフトウェアエンジニアリング',
    investmentBanking: '投資銀行',
    medicalResidency: '医学研修',
    quantitativeResearcher: '量的研究者',
    managementConsulting: '経営コンサルティング',
    criminalLawyer: '刑事弁護士',
    electricalEngineer: '電気技師',
    productManager: 'プロダクトマネージャー',
  },
  Korean: {
    skip: '건너뛰기',
    next: '다음',
    back: '뒤로',
    welcomeTo: '환영합니다',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: '당신의 학습 여정이 여기서 시작됩니다',
    whatAreYouPreppingFor: '무엇을 준비하고 계신가요?',
    studyPrep: '학습',
    interviewPrep: '면접',
    selectLanguage: '언어 선택',
    great: '훌륭해요!',
    justAFewMoreQuestions: '시작하기 위해 몇 가지 질문만 더...',
    progress: '1/3',
    whichSubjects: '어떤 과목을 준비하고 계신가요?',
    // Study subjects
    history: '역사',
    physics: '물리학',
    chemistry: '화학',
    biology: '생물학',
    geography: '지리학',
    math: '수학',
    medicine: '의학',
    law: '법학',
    finance: '금융',
    computing: '컴퓨팅',
    // Interview subjects
    softwareEngineering: '소프트웨어 엔지니어링',
    investmentBanking: '투자 은행',
    medicalResidency: '의료 레지던트',
    quantitativeResearcher: '정량 연구원',
    managementConsulting: '경영 컨설팅',
    criminalLawyer: '형사 변호사',
    electricalEngineer: '전기 엔지니어',
    productManager: '제품 관리자',
  },
  Spanish: {
    skip: 'Omitir',
    next: 'Siguiente',
    back: 'Atrás',
    welcomeTo: 'Bienvenido a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Tu viaje de aprendizaje comienza aquí',
    whatAreYouPreppingFor: '¿Para qué te estás preparando?',
    studyPrep: 'Estudios',
    interviewPrep: 'Entrevistas',
    selectLanguage: 'Seleccionar Idioma',
    great: '¡Genial!',
    justAFewMoreQuestions: 'Solo unas preguntas más para comenzar...',
    progress: '1/3',
    whichSubjects: '¿Para qué materia(s) te estás preparando?',
    // Study subjects
    history: 'Historia',
    physics: 'Física',
    chemistry: 'Química',
    biology: 'Biología',
    geography: 'Geografía',
    math: 'Matemáticas',
    medicine: 'Medicina',
    law: 'Derecho',
    finance: 'Finanzas',
    computing: 'Informática',
    // Interview subjects
    softwareEngineering: 'Ingeniería de Software',
    investmentBanking: 'Banca de Inversión',
    medicalResidency: 'Residencia Médica',
    quantitativeResearcher: 'Investigador Cuantitativo',
    managementConsulting: 'Consultoría de Gestión',
    criminalLawyer: 'Abogado Penal',
    electricalEngineer: 'Ingeniero Eléctrico',
    productManager: 'Gerente de Producto',
  },
  German: {
    skip: 'Überspringen',
    next: 'Weiter',
    back: 'Zurück',
    welcomeTo: 'Willkommen bei',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ihre Lernreise beginnt hier',
    whatAreYouPreppingFor: 'Wofür bereiten Sie sich vor?',
    studyPrep: 'Studium',
    interviewPrep: 'Vorstellungsgespräch',
    selectLanguage: 'Sprache auswählen',
    great: 'Großartig!',
    justAFewMoreQuestions: 'Nur noch ein paar Fragen, um loszulegen...',
    progress: '1/3',
    whichSubjects: 'Für welche Fächer bereiten Sie sich vor?',
    // Study subjects
    history: 'Geschichte',
    physics: 'Physik',
    chemistry: 'Chemie',
    biology: 'Biologie',
    geography: 'Geographie',
    math: 'Mathematik',
    medicine: 'Medizin',
    law: 'Recht',
    finance: 'Finanzen',
    computing: 'Informatik',
    // Interview subjects
    softwareEngineering: 'Softwaretechnik',
    investmentBanking: 'Investment Banking',
    medicalResidency: 'Medizinisches Praktikum',
    quantitativeResearcher: 'Quantitativer Forscher',
    managementConsulting: 'Unternehmensberatung',
    criminalLawyer: 'Strafverteidiger',
    electricalEngineer: 'Elektroingenieur',
    productManager: 'Produktmanager',
  },
  Portuguese: {
    skip: 'Pular',
    next: 'Próximo',
    back: 'Voltar',
    welcomeTo: 'Bem-vindo ao',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Sua jornada de aprendizado começa aqui',
    whatAreYouPreppingFor: 'Para o que você está se preparando?',
    studyPrep: 'Estudos',
    interviewPrep: 'Entrevistas',
    selectLanguage: 'Selecionar Idioma',
    great: 'Ótimo!',
    justAFewMoreQuestions: 'Apenas algumas perguntas mais para começar...',
    progress: '1/3',
    whichSubjects: 'Para quais matérias você está se preparando?',
    // Study subjects
    history: 'História',
    physics: 'Física',
    chemistry: 'Química',
    biology: 'Biologia',
    geography: 'Geografia',
    math: 'Matemática',
    medicine: 'Medicina',
    law: 'Direito',
    finance: 'Finanças',
    computing: 'Informática',
    // Interview subjects
    softwareEngineering: 'Engenharia de Software',
    investmentBanking: 'Banco de Investimento',
    medicalResidency: 'Residência Médica',
    quantitativeResearcher: 'Pesquisador Quantitativo',
    managementConsulting: 'Consultoria de Gestão',
    criminalLawyer: 'Advogado Criminal',
    electricalEngineer: 'Engenheiro Elétrico',
    productManager: 'Gerente de Produto',
  },
  Italian: {
    skip: 'Salta',
    next: 'Avanti',
    back: 'Indietro',
    welcomeTo: 'Benvenuto a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Il tuo viaggio di apprendimento inizia qui',
    whatAreYouPreppingFor: 'Per cosa ti stai preparando?',
    studyPrep: 'Studi',
    interviewPrep: 'Colloqui',
    selectLanguage: 'Seleziona Lingua',
    great: 'Fantastico!',
    justAFewMoreQuestions: 'Solo alcune domande in più per iniziare...',
    progress: '1/3',
    whichSubjects: 'Per quali materie ti stai preparando?',
    // Study subjects
    history: 'Storia',
    physics: 'Fisica',
    chemistry: 'Chimica',
    biology: 'Biologia',
    geography: 'Geografia',
    math: 'Matematica',
    medicine: 'Medicina',
    law: 'Diritto',
    finance: 'Finanza',
    computing: 'Informatica',
    // Interview subjects
    softwareEngineering: 'Ingegneria del Software',
    investmentBanking: 'Banca di Investimento',
    medicalResidency: 'Residenza Medica',
    quantitativeResearcher: 'Ricercatore Quantitativo',
    managementConsulting: 'Consulenza di Gestione',
    criminalLawyer: 'Avvocato Penale',
    electricalEngineer: 'Ingegnere Elettrico',
    productManager: 'Product Manager',
  },
  Russian: {
    skip: 'Пропустить',
    next: 'Далее',
    back: 'Назад',
    welcomeTo: 'Добро пожаловать в',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ваше путешествие в обучении начинается здесь',
    whatAreYouPreppingFor: 'К чему вы готовитесь?',
    studyPrep: 'Учеба',
    interviewPrep: 'Собеседование',
    selectLanguage: 'Выберите Язык',
    great: 'Отлично!',
    justAFewMoreQuestions: 'Еще несколько вопросов, чтобы начать...',
    progress: '1/3',
    whichSubjects: 'По каким предметам вы готовитесь?',
    // Study subjects
    history: 'История',
    physics: 'Физика',
    chemistry: 'Химия',
    biology: 'Биология',
    geography: 'География',
    math: 'Математика',
    medicine: 'Медицина',
    law: 'Право',
    finance: 'Финансы',
    computing: 'Информатика',
    // Interview subjects
    softwareEngineering: 'Разработка ПО',
    investmentBanking: 'Инвестиционный банкинг',
    medicalResidency: 'Медицинская ординатура',
    quantitativeResearcher: 'Количественный исследователь',
    managementConsulting: 'Управленческий консалтинг',
    criminalLawyer: 'Уголовный адвокат',
    electricalEngineer: 'Инженер-электрик',
    productManager: 'Менеджер по продукту',
  },
  Arabic: {
    skip: 'تخطي',
    next: 'التالي',
    back: 'رجوع',
    welcomeTo: 'مرحباً بك في',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'رحلتك التعليمية تبدأ من هنا',
    whatAreYouPreppingFor: 'لماذا تستعد؟',
    studyPrep: 'الدراسة',
    interviewPrep: 'المقابلة',
    selectLanguage: 'اختر اللغة',
    great: 'رائع!',
    justAFewMoreQuestions: 'بضع أسئلة أخرى للبدء...',
    progress: '1/3',
    whichSubjects: 'أي مادة تحضر لها؟',
    // Study subjects
    history: 'التاريخ',
    physics: 'الفيزياء',
    chemistry: 'الكيمياء',
    biology: 'الأحياء',
    geography: 'الجغرافيا',
    math: 'الرياضيات',
    medicine: 'الطب',
    law: 'القانون',
    finance: 'المالية',
    computing: 'الحاسوب',
    // Interview subjects
    softwareEngineering: 'هندسة البرمجيات',
    investmentBanking: 'البنوك الاستثمارية',
    medicalResidency: 'الإقامة الطبية',
    quantitativeResearcher: 'باحث كمي',
    managementConsulting: 'الاستشارات الإدارية',
    criminalLawyer: 'محامي جنائي',
    electricalEngineer: 'مهندس كهربائي',
    productManager: 'مدير المنتج',
  },
  Indonesian: {
    skip: 'Lewati',
    next: 'Selanjutnya',
    back: 'Kembali',
    welcomeTo: 'Selamat datang di',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Perjalanan belajar Anda dimulai di sini',
    whatAreYouPreppingFor: 'Untuk apa Anda mempersiapkan diri?',
    studyPrep: 'Belajar',
    interviewPrep: 'Wawancara',
    selectLanguage: 'Pilih Bahasa',
    great: 'Hebat!',
    justAFewMoreQuestions: 'Beberapa pertanyaan lagi untuk memulai...',
    progress: '1/3',
    whichSubjects: 'Mata pelajaran apa yang Anda persiapkan?',
    // Study subjects
    history: 'Sejarah',
    physics: 'Fisika',
    chemistry: 'Kimia',
    biology: 'Biologi',
    geography: 'Geografi',
    math: 'Matematika',
    medicine: 'Kedokteran',
    law: 'Hukum',
    finance: 'Keuangan',
    computing: 'Komputasi',
    // Interview subjects
    softwareEngineering: 'Teknik Perangkat Lunak',
    investmentBanking: 'Perbankan Investasi',
    medicalResidency: 'Residensi Medis',
    quantitativeResearcher: 'Peneliti Kuantitatif',
    managementConsulting: 'Konsultasi Manajemen',
    criminalLawyer: 'Pengacara Kriminal',
    electricalEngineer: 'Insinyur Listrik',
    productManager: 'Manajer Produk',
  },
  Thai: {
    skip: 'ข้าม',
    next: 'ถัดไป',
    back: 'กลับ',
    welcomeTo: 'ยินดีต้อนรับสู่',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'การเดินทางเรียนรู้ของคุณเริ่มต้นที่นี่',
    whatAreYouPreppingFor: 'คุณกำลังเตรียมตัวสำหรับอะไร?',
    studyPrep: 'การเรียน',
    interviewPrep: 'การสัมภาษณ์',
    selectLanguage: 'เลือกภาษา',
    great: 'เยี่ยม!',
    justAFewMoreQuestions: 'คำถามอีกไม่กี่ข้อเพื่อเริ่มต้น...',
    progress: '1/3',
    whichSubjects: 'คุณกำลังเตรียมตัวสำหรับวิชาใด?',
    // Study subjects
    history: 'ประวัติศาสตร์',
    physics: 'ฟิสิกส์',
    chemistry: 'เคมี',
    biology: 'ชีววิทยา',
    geography: 'ภูมิศาสตร์',
    math: 'คณิตศาสตร์',
    medicine: 'การแพทย์',
    law: 'กฎหมาย',
    finance: 'การเงิน',
    computing: 'การคำนวณ',
    // Interview subjects
    softwareEngineering: 'วิศวกรรมซอฟต์แวร์',
    investmentBanking: 'ธนาคารการลงทุน',
    medicalResidency: 'การฝึกงานแพทย์',
    quantitativeResearcher: 'นักวิจัยเชิงปริมาณ',
    managementConsulting: 'ที่ปรึกษาด้านการจัดการ',
    criminalLawyer: 'ทนายความคดีอาญา',
    electricalEngineer: 'วิศวกรไฟฟ้า',
    productManager: 'ผู้จัดการผลิตภัณฑ์',
  },
  Vietnamese: {
    skip: 'Bỏ qua',
    next: 'Tiếp theo',
    back: 'Quay lại',
    welcomeTo: 'Chào mừng đến với',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Hành trình học tập của bạn bắt đầu từ đây',
    whatAreYouPreppingFor: 'Bạn đang chuẩn bị cho gì?',
    studyPrep: 'Học tập',
    interviewPrep: 'Phỏng vấn',
    selectLanguage: 'Chọn Ngôn ngữ',
    great: 'Tuyệt vời!',
    justAFewMoreQuestions: 'Chỉ còn một vài câu hỏi nữa để bắt đầu...',
    progress: '1/3',
    whichSubjects: 'Bạn đang chuẩn bị cho môn học nào?',
    // Study subjects
    history: 'Lịch sử',
    physics: 'Vật lý',
    chemistry: 'Hóa học',
    biology: 'Sinh học',
    geography: 'Địa lý',
    math: 'Toán học',
    medicine: 'Y học',
    law: 'Luật',
    finance: 'Tài chính',
    computing: 'Tin học',
    // Interview subjects
    softwareEngineering: 'Kỹ thuật phần mềm',
    investmentBanking: 'Ngân hàng đầu tư',
    medicalResidency: 'Nội trú y khoa',
    quantitativeResearcher: 'Nhà nghiên cứu định lượng',
    managementConsulting: 'Tư vấn quản lý',
    criminalLawyer: 'Luật sư hình sự',
    electricalEngineer: 'Kỹ sư điện',
    productManager: 'Quản lý sản phẩm',
  },
  Turkish: {
    skip: 'Atla',
    next: 'İleri',
    back: 'Geri',
    welcomeTo: 'Hoş geldiniz',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Öğrenme yolculuğunuz burada başlıyor',
    whatAreYouPreppingFor: 'Neye hazırlanıyorsunuz?',
    studyPrep: 'Çalışma',
    interviewPrep: 'Mülakat',
    selectLanguage: 'Dil Seçin',
    great: 'Harika!',
    justAFewMoreQuestions: 'Başlamak için sadece birkaç soru daha...',
    progress: '1/3',
    whichSubjects: 'Hangi konulara hazırlanıyorsunuz?',
    // Study subjects
    history: 'Tarih',
    physics: 'Fizik',
    chemistry: 'Kimya',
    biology: 'Biyoloji',
    geography: 'Coğrafya',
    math: 'Matematik',
    medicine: 'Tıp',
    law: 'Hukuk',
    finance: 'Finans',
    computing: 'Bilgisayar',
    // Interview subjects
    softwareEngineering: 'Yazılım Mühendisliği',
    investmentBanking: 'Yatırım Bankacılığı',
    medicalResidency: 'Tıbbi İhtisas',
    quantitativeResearcher: 'Kantitatif Araştırmacı',
    managementConsulting: 'Yönetim Danışmanlığı',
    criminalLawyer: 'Ceza Avukatı',
    electricalEngineer: 'Elektrik Mühendisi',
    productManager: 'Ürün Müdürü',
  },
  Dutch: {
    skip: 'Overslaan',
    next: 'Volgende',
    back: 'Terug',
    welcomeTo: 'Welkom bij',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Uw leerreis begint hier',
    whatAreYouPreppingFor: 'Waar bereidt u zich op voor?',
    studyPrep: 'Studie',
    interviewPrep: 'Sollicitatie',
    selectLanguage: 'Selecteer Taal',
    great: 'Geweldig!',
    justAFewMoreQuestions: 'Nog een paar vragen om te beginnen...',
    progress: '1/3',
    whichSubjects: 'Voor welke vakken bereid je je voor?',
    // Study subjects
    history: 'Geschiedenis',
    physics: 'Natuurkunde',
    chemistry: 'Scheikunde',
    biology: 'Biologie',
    geography: 'Aardrijkskunde',
    math: 'Wiskunde',
    medicine: 'Geneeskunde',
    law: 'Rechten',
    finance: 'Financiën',
    computing: 'Informatica',
    // Interview subjects
    softwareEngineering: 'Software Engineering',
    investmentBanking: 'Investment Banking',
    medicalResidency: 'Medische Specialisatie',
    quantitativeResearcher: 'Kwantitatief Onderzoeker',
    managementConsulting: 'Management Consulting',
    criminalLawyer: 'Strafrechtadvocaat',
    electricalEngineer: 'Elektrotechnisch Ingenieur',
    productManager: 'Product Manager',
  },
  Polish: {
    skip: 'Pomiń',
    next: 'Dalej',
    back: 'Wstecz',
    welcomeTo: 'Witamy w',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Twoja podróż edukacyjna zaczyna się tutaj',
    whatAreYouPreppingFor: 'Na co się przygotowujesz?',
    studyPrep: 'Studia',
    interviewPrep: 'Rozmowa',
    selectLanguage: 'Wybierz Język',
    great: 'Świetnie!',
    justAFewMoreQuestions: 'Jeszcze kilka pytań, aby zacząć...',
    progress: '1/3',
    whichSubjects: 'Do jakich przedmiotów się przygotowujesz?',
    // Study subjects
    history: 'Historia',
    physics: 'Fizyka',
    chemistry: 'Chemia',
    biology: 'Biologia',
    geography: 'Geografia',
    math: 'Matematyka',
    medicine: 'Medycyna',
    law: 'Prawo',
    finance: 'Finanse',
    computing: 'Informatyka',
    // Interview subjects
    softwareEngineering: 'Inżynieria Oprogramowania',
    investmentBanking: 'Bankowość Inwestycyjna',
    medicalResidency: 'Specjalizacja Medyczna',
    quantitativeResearcher: 'Badacz Ilościowy',
    managementConsulting: 'Doradztwo Zarządcze',
    criminalLawyer: 'Adwokat Karny',
    electricalEngineer: 'Inżynier Elektryk',
    productManager: 'Menedżer Produktu',
  },
  Swedish: {
    skip: 'Hoppa över',
    next: 'Nästa',
    back: 'Tillbaka',
    welcomeTo: 'Välkommen till',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din inlärningsresa börjar här',
    whatAreYouPreppingFor: 'För vad förbereder du dig?',
    studyPrep: 'Studier',
    interviewPrep: 'Intervju',
    selectLanguage: 'Välj Språk',
    great: 'Fantastiskt!',
    justAFewMoreQuestions: 'Bara några frågor till för att komma igång...',
    progress: '1/3',
    whichSubjects: 'Vilka ämnen förbereder du dig för?',
    // Study subjects
    history: 'Historia',
    physics: 'Fysik',
    chemistry: 'Kemi',
    biology: 'Biologi',
    geography: 'Geografi',
    math: 'Matematik',
    medicine: 'Medicin',
    law: 'Juridik',
    finance: 'Finans',
    computing: 'Datavetenskap',
    // Interview subjects
    softwareEngineering: 'Mjukvaruutveckling',
    investmentBanking: 'Investment Banking',
    medicalResidency: 'Medicinsk Specialisering',
    quantitativeResearcher: 'Kvantitativ Forskare',
    managementConsulting: 'Management Consulting',
    criminalLawyer: 'Brottmålsadvokat',
    electricalEngineer: 'Elektroingenjör',
    productManager: 'Produktchef',
  },
  Czech: {
    skip: 'Přeskočit',
    next: 'Další',
    back: 'Zpět',
    welcomeTo: 'Vítejte v',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Vaše vzdělávací cesta začíná zde',
    whatAreYouPreppingFor: 'Na co se připravujete?',
    studyPrep: 'Studium',
    interviewPrep: 'Rozhovor',
    selectLanguage: 'Vyberte Jazyk',
    great: 'Skvělé!',
    justAFewMoreQuestions: 'Ještě několik otázek k začátku...',
    progress: '1/3',
    whichSubjects: 'Pro jaké předměty se připravujete?',
    // Study subjects
    history: 'Dějepis',
    physics: 'Fyzika',
    chemistry: 'Chemie',
    biology: 'Biologie',
    geography: 'Zeměpis',
    math: 'Matematika',
    medicine: 'Medicína',
    law: 'Právo',
    finance: 'Finance',
    computing: 'Informatika',
    // Interview subjects
    softwareEngineering: 'Vývoj softwaru',
    investmentBanking: 'Investment Banking',
    medicalResidency: 'Lékařská specializace',
    quantitativeResearcher: 'Kvantitativní výzkumník',
    managementConsulting: 'Management Consulting',
    criminalLawyer: 'Trestní právník',
    electricalEngineer: 'Elektrotechnický inženýr',
    productManager: 'Produktový manažer',
  },
  Greek: {
    skip: 'Παράλειψη',
    next: 'Επόμενο',
    back: 'Πίσω',
    welcomeTo: 'Καλώς ήρθατε στο',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Το ταξίδι μάθησής σας ξεκινά εδώ',
    whatAreYouPreppingFor: 'Για τι προετοιμάζεστε;',
    studyPrep: 'Σπουδές',
    interviewPrep: 'Συνέντευξη',
    selectLanguage: 'Επιλέξτε Γλώσσα',
    great: 'Τέλεια!',
    justAFewMoreQuestions: 'Μόνο λίγες ακόμα ερωτήσεις για να ξεκινήσετε...',
    progress: '1/3',
    whichSubjects: 'Για ποια μαθήματα προετοιμάζεστε;',
    // Study subjects
    history: 'Ιστορία',
    physics: 'Φυσική',
    chemistry: 'Χημεία',
    biology: 'Βιολογία',
    geography: 'Γεωγραφία',
    math: 'Μαθηματικά',
    medicine: 'Ιατρική',
    law: 'Δίκαιο',
    finance: 'Οικονομικά',
    computing: 'Πληροφορική',
    // Interview subjects
    softwareEngineering: 'Μηχανική Λογισμικού',
    investmentBanking: 'Τραπεζική Επένδυσης',
    medicalResidency: 'Ιατρική Ειδικότητα',
    quantitativeResearcher: 'Ποσοτικός Ερευνητής',
    managementConsulting: 'Συμβουλευτική Διοίκησης',
    criminalLawyer: 'Ποινικός Δικηγόρος',
    electricalEngineer: 'Ηλεκτρολόγος Μηχανικός',
    productManager: 'Διαχειριστής Προϊόντος',
  },
  Hebrew: {
    skip: 'דלג',
    next: 'הבא',
    back: 'חזור',
    welcomeTo: 'ברוכים הבאים ל',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'מסע הלמידה שלכם מתחיל כאן',
    whatAreYouPreppingFor: 'למה אתם מתכוננים?',
    studyPrep: 'לימודים',
    interviewPrep: 'ראיון',
    selectLanguage: 'בחר שפה',
    great: 'נהדר!',
    justAFewMoreQuestions: 'רק עוד כמה שאלות כדי להתחיל...',
    progress: '1/3',
    whichSubjects: 'איזה נושאים אתם מתכוננים?',
    // Study subjects
    history: 'היסטוריה',
    physics: 'פיזיקה',
    chemistry: 'כימיה',
    biology: 'ביולוגיה',
    geography: 'גיאוגרפיה',
    math: 'מתמטיקה',
    medicine: 'רפואה',
    law: 'משפטים',
    finance: 'פיננסים',
    computing: 'מחשבים',
    // Interview subjects
    softwareEngineering: 'הנדסת תוכנה',
    investmentBanking: 'בנקאות השקעות',
    medicalResidency: 'התמחות רפואית',
    quantitativeResearcher: 'חוקר כמותי',
    managementConsulting: 'ייעוץ ניהולי',
    criminalLawyer: 'עורך דין פלילי',
    electricalEngineer: 'מהנדס חשמל',
    productManager: 'מנהל מוצר',
  },
  Tagalog: {
    skip: 'Laktawan',
    next: 'Susunod',
    back: 'Balik',
    welcomeTo: 'Maligayang pagdating sa',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ang inyong pag-aaral na paglalakbay ay nagsisimula dito',
    whatAreYouPreppingFor: 'Para saan kayo naghahanda?',
    studyPrep: 'Pag-aaral',
    interviewPrep: 'Panayam',
    selectLanguage: 'Pumili ng Wika',
    great: 'Mahusay!',
    justAFewMoreQuestions: 'Ilang tanong pa lang para makapagsimula...',
    progress: '1/3',
    whichSubjects: 'Para saang mga paksa kayo naghahanda?',
    // Study subjects
    history: 'Kasaysayan',
    physics: 'Pisika',
    chemistry: 'Kemistri',
    biology: 'Biyolohiya',
    geography: 'Heograpiya',
    math: 'Matematika',
    medicine: 'Medisina',
    law: 'Batas',
    finance: 'Pananalapi',
    computing: 'Kompyuter',
    // Interview subjects
    softwareEngineering: 'Software Engineering',
    investmentBanking: 'Investment Banking',
    medicalResidency: 'Medical Residency',
    quantitativeResearcher: 'Quantitative Researcher',
    managementConsulting: 'Management Consulting',
    criminalLawyer: 'Criminal Lawyer',
    electricalEngineer: 'Electrical Engineer',
    productManager: 'Product Manager',
  },
  Tamil: {
    skip: 'தவிர்க்க',
    next: 'அடுத்து',
    back: 'திரும்பு',
    welcomeTo: 'வரவேற்கிறோம்',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'உங்கள் கற்றல் பயணம் இங்கே தொடங்குகிறது',
    whatAreYouPreppingFor: 'நீங்கள் எதற்காக தயாராகிறீர்கள்?',
    studyPrep: 'படிப்பு',
    interviewPrep: 'நேர்காணல்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    great: 'அருமை!',
    justAFewMoreQuestions: 'தொடங்க சில கேள்விகள் மட்டும்...',
    progress: '1/3',
    whichSubjects: 'நீங்கள் எந்த பாடங்களுக்கு தயாராகிறீர்கள்?',
    // Study subjects
    history: 'வரலாறு',
    physics: 'இயற்பியல்',
    chemistry: 'வேதியியல்',
    biology: 'உயிரியல்',
    geography: 'புவியியல்',
    math: 'கணிதம்',
    medicine: 'மருத்துவம்',
    law: 'சட்டம்',
    finance: 'நிதி',
    computing: 'கணினியியல்',
    // Interview subjects
    softwareEngineering: 'மென்பொருள் பொறியியல்',
    investmentBanking: 'முதலீட்டு வங்கியியல்',
    medicalResidency: 'மருத்துவ பயிற்சி',
    quantitativeResearcher: 'அளவீட்டு ஆராய்ச்சியாளர்',
    managementConsulting: 'மேலாண்மை ஆலோசனை',
    criminalLawyer: 'குற்றவியல் வழக்கறிஞர்',
    electricalEngineer: 'மின் பொறியாளர்',
    productManager: 'தயாரிப்பு மேலாளர்',
  },
  Bengali: {
    skip: 'এড়িয়ে যান',
    next: 'পরবর্তী',
    back: 'ফিরে যান',
    welcomeTo: 'স্বাগতম',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'আপনার শেখার যাত্রা এখান থেকে শুরু হয়',
    whatAreYouPreppingFor: 'আপনি কোনটির জন্য প্রস্তুত হচ্ছেন?',
    studyPrep: 'পড়াশোনা',
    interviewPrep: 'সাক্ষাত্কার',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    great: 'দারুণ!',
    justAFewMoreQuestions: 'শুরু করার জন্য আরও কয়েকটি প্রশ্ন...',
    progress: '1/3',
    whichSubjects: 'আপনি কোন বিষয়ের জন্য প্রস্তুত হচ্ছেন?',
    // Study subjects
    history: 'ইতিহাস',
    physics: 'পদার্থবিজ্ঞান',
    chemistry: 'রসায়ন',
    biology: 'জীববিজ্ঞান',
    geography: 'ভূগোল',
    math: 'গণিত',
    medicine: 'চিকিৎসা',
    law: 'আইন',
    finance: 'অর্থ',
    computing: 'কম্পিউটিং',
    // Interview subjects
    softwareEngineering: 'সফটওয়্যার ইঞ্জিনিয়ারিং',
    investmentBanking: 'বিনিয়োগ ব্যাংকিং',
    medicalResidency: 'মেডিকেল রেসিডেন্সি',
    quantitativeResearcher: 'পরিমাণগত গবেষক',
    managementConsulting: 'ব্যবস্থাপনা পরামর্শ',
    criminalLawyer: 'অপরাধী আইনজীবী',
    electricalEngineer: 'তড়িৎ প্রকৌশলী',
    productManager: 'পণ্য ব্যবস্থাপক',
  },
  Ukrainian: {
    skip: 'Пропустити',
    next: 'Далі',
    back: 'Назад',
    welcomeTo: 'Ласкаво просимо до',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Ваша подорож навчання починається тут',
    whatAreYouPreppingFor: 'До чого ви готуєтеся?',
    studyPrep: 'Навчання',
    interviewPrep: 'Співбесіда',
    selectLanguage: 'Оберіть Мову',
    great: 'Чудово!',
    justAFewMoreQuestions: 'Ще кілька питань для початку...',
    progress: '1/3',
    whichSubjects: 'З яких предметів ви готуєтеся?',
    // Study subjects
    history: 'Історія',
    physics: 'Фізика',
    chemistry: 'Хімія',
    biology: 'Біологія',
    geography: 'Географія',
    math: 'Математика',
    medicine: 'Медицина',
    law: 'Право',
    finance: 'Фінанси',
    computing: 'Інформатика',
    // Interview subjects
    softwareEngineering: 'Розробка ПЗ',
    investmentBanking: 'Інвестиційний банкінг',
    medicalResidency: 'Медична ординатура',
    quantitativeResearcher: 'Кількісний дослідник',
    managementConsulting: 'Управлінське консультування',
    criminalLawyer: 'Кримінальний адвокат',
    electricalEngineer: 'Інженер-електрик',
    productManager: 'Менеджер продукту',
  },
  Romanian: {
    skip: 'Omite',
    next: 'Următorul',
    back: 'Înapoi',
    welcomeTo: 'Bun venit la',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Călătoria ta de învățare începe aici',
    whatAreYouPreppingFor: 'Pentru ce te pregătești?',
    studyPrep: 'Studii',
    interviewPrep: 'Interviu',
    selectLanguage: 'Selectează Limba',
    great: 'Minunat!',
    justAFewMoreQuestions: 'Doar câteva întrebări în plus pentru a începe...',
    progress: '1/3',
    whichSubjects: 'Pentru ce materii te pregătești?',
    // Study subjects
    history: 'Istorie',
    physics: 'Fizică',
    chemistry: 'Chimie',
    biology: 'Biologie',
    geography: 'Geografie',
    math: 'Matematică',
    medicine: 'Medicină',
    law: 'Drept',
    finance: 'Finanțe',
    computing: 'Informatică',
    // Interview subjects
    softwareEngineering: 'Inginerie Software',
    investmentBanking: 'Banking de Investiții',
    medicalResidency: 'Rezidențiat Medical',
    quantitativeResearcher: 'Cercetător Cantitativ',
    managementConsulting: 'Consulting în Management',
    criminalLawyer: 'Avocat Penal',
    electricalEngineer: 'Inginer Electrician',
    productManager: 'Manager de Produs',
  },
  Hungarian: {
    skip: 'Kihagyás',
    next: 'Következő',
    back: 'Vissza',
    welcomeTo: 'Üdvözöljük a',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'A tanulási utazásod itt kezdődik',
    whatAreYouPreppingFor: 'Mire készülsz fel?',
    studyPrep: 'Tanulmány',
    interviewPrep: 'Interjú',
    selectLanguage: 'Válassz Nyelvet',
    great: 'Nagyszerű!',
    justAFewMoreQuestions: 'Csak néhány kérdés még, hogy elkezdhesd...',
    progress: '1/3',
    whichSubjects: 'Milyen tantárgyakhoz készülsz fel?',
    // Study subjects
    history: 'Történelem',
    physics: 'Fizika',
    chemistry: 'Kémia',
    biology: 'Biológia',
    geography: 'Földrajz',
    math: 'Matematika',
    medicine: 'Orvostudomány',
    law: 'Jog',
    finance: 'Pénzügy',
    computing: 'Számítástechnika',
    // Interview subjects
    softwareEngineering: 'Szoftverfejlesztés',
    investmentBanking: 'Befektetési Bank',
    medicalResidency: 'Orvosi Szakvizsga',
    quantitativeResearcher: 'Kvantitatív Kutató',
    managementConsulting: 'Menedzsment Tanácsadás',
    criminalLawyer: 'Büntetőjog Ügyvéd',
    electricalEngineer: 'Elektromérnök',
    productManager: 'Termék Menedzser',
  },
  Farsi: {
    skip: 'رد کردن',
    next: 'بعدی',
    back: 'بازگشت',
    welcomeTo: 'خوش آمدید به',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'سفر یادگیری شما از اینجا آغاز می‌شود',
    whatAreYouPreppingFor: 'برای چه چیزی آماده می‌شوید؟',
    studyPrep: 'تحصیل',
    interviewPrep: 'مصاحبه',
    selectLanguage: 'انتخاب زبان',
    great: 'عالی!',
    justAFewMoreQuestions: 'فقط چند سؤال دیگر برای شروع...',
    progress: '1/3',
    whichSubjects: 'برای چه موضوعاتی آماده می‌شوید؟',
    // Study subjects
    history: 'تاریخ',
    physics: 'فیزیک',
    chemistry: 'شیمی',
    biology: 'زیست شناسی',
    geography: 'جغرافیا',
    math: 'ریاضیات',
    medicine: 'پزشکی',
    law: 'حقوق',
    finance: 'مالی',
    computing: 'کامپیوتر',
    // Interview subjects
    softwareEngineering: 'مهندسی نرم‌افزار',
    investmentBanking: 'بانکداری سرمایه‌گذاری',
    medicalResidency: 'دستیاری پزشکی',
    quantitativeResearcher: 'محقق کمی',
    managementConsulting: 'مشاوره مدیریت',
    criminalLawyer: 'وکیل جنایی',
    electricalEngineer: 'مهندس برق',
    productManager: 'مدیر محصول',
  },
  Swahili: {
    skip: 'Ruka',
    next: 'Ifuatayo',
    back: 'Rudi',
    welcomeTo: 'Karibu',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Safari yako ya kujifunza inaanza hapa',
    whatAreYouPreppingFor: 'Unajiandaa kwa nini?',
    studyPrep: 'Masomo',
    interviewPrep: 'Mahojiano',
    selectLanguage: 'Chagua Lugha',
    great: 'Vizuri!',
    justAFewMoreQuestions: 'Maswali machache tu ya kuanza...',
    progress: '1/3',
    whichSubjects: 'Unaandaa masomo gani?',
    // Study subjects
    history: 'Historia',
    physics: 'Fizikia',
    chemistry: 'Kemia',
    biology: 'Biolojia',
    geography: 'Jiografia',
    math: 'Hisabati',
    medicine: 'Dawa',
    law: 'Sheria',
    finance: 'Fedha',
    computing: 'Kompyuta',
    // Interview subjects
    softwareEngineering: 'Uhandisi wa Programu',
    investmentBanking: 'Benki ya Uwekezaji',
    medicalResidency: 'Ualimu wa Matibabu',
    quantitativeResearcher: 'Mtafiti wa Idadi',
    managementConsulting: 'Ushauri wa Usimamizi',
    criminalLawyer: 'Mwanasheria wa Jinai',
    electricalEngineer: 'Mhandisi wa Umeme',
    productManager: 'Msimamizi wa Bidhaa',
  },
  Afrikaans: {
    skip: 'Slaan Oor',
    next: 'Volgende',
    back: 'Terug',
    welcomeTo: 'Welkom by',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Jou leerreis begin hier',
    whatAreYouPreppingFor: 'Waarvoor berei jy jou voor?',
    studyPrep: 'Studie',
    interviewPrep: 'Onderhoud',
    selectLanguage: 'Kies Taal',
    great: 'Geweldig!',
    justAFewMoreQuestions: 'Net nog \'n paar vrae om te begin...',
    progress: '1/3',
    whichSubjects: 'Vir watter vakke berei jy jou voor?',
    // Study subjects
    history: 'Geskiedenis',
    physics: 'Fisika',
    chemistry: 'Chemie',
    biology: 'Biologie',
    geography: 'Geografie',
    math: 'Wiskunde',
    medicine: 'Medisyne',
    law: 'Reg',
    finance: 'Finansies',
    computing: 'Rekenaarwetenskap',
    // Interview subjects
    softwareEngineering: 'Sagteware Ingenieurswese',
    investmentBanking: 'Beleggingsbank',
    medicalResidency: 'Mediese Spesialisering',
    quantitativeResearcher: 'Kwantitatiewe Navorser',
    managementConsulting: 'Bestuurskonsultasie',
    criminalLawyer: 'Kriminele Prokureur',
    electricalEngineer: 'Elektriese Ingenieur',
    productManager: 'Produkbestuurder',
  },
  Finnish: {
    skip: 'Ohita',
    next: 'Seuraava',
    back: 'Takaisin',
    welcomeTo: 'Tervetuloa',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Oppimismatkasi alkaa täältä',
    whatAreYouPreppingFor: 'Mihin valmistaudut?',
    studyPrep: 'Opiskelu',
    interviewPrep: 'Haastattelu',
    selectLanguage: 'Valitse Kieli',
    great: 'Hienoa!',
    justAFewMoreQuestions: 'Vain muutama kysymys lisää aloittamiseen...',
    progress: '1/3',
    whichSubjects: 'Mihin aineisiin valmistaudut?',
    // Study subjects
    history: 'Historia',
    physics: 'Fysiikka',
    chemistry: 'Kemia',
    biology: 'Biologia',
    geography: 'Maantiede',
    math: 'Matematiikka',
    medicine: 'Lääketiede',
    law: 'Oikeustiede',
    finance: 'Rahoitus',
    computing: 'Tietojenkäsittely',
    // Interview subjects
    softwareEngineering: 'Ohjelmistotekniikka',
    investmentBanking: 'Sijoituspankki',
    medicalResidency: 'Lääketieteellinen erikoistumiskoulutus',
    quantitativeResearcher: 'Kvantitatiivinen tutkija',
    managementConsulting: 'Johtamiskonsultointi',
    criminalLawyer: 'Rikosoikeuden asianajaja',
    electricalEngineer: 'Sähköinsinööri',
    productManager: 'Tuotepäällikkö',
  },
  Norwegian: {
    skip: 'Hopp Over',
    next: 'Neste',
    back: 'Tilbake',
    welcomeTo: 'Velkommen til',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din læringsreise begynner her',
    whatAreYouPreppingFor: 'Hva forbereder du deg på?',
    studyPrep: 'Studie',
    interviewPrep: 'Intervju',
    selectLanguage: 'Velg Språk',
    great: 'Flott!',
    justAFewMoreQuestions: 'Bare noen få spørsmål til for å komme i gang...',
    progress: '1/3',
    whichSubjects: 'Hvilke fag forbereder du deg på?',
    // Study subjects
    history: 'Historie',
    physics: 'Fysikk',
    chemistry: 'Kjemi',
    biology: 'Biologi',
    geography: 'Geografi',
    math: 'Matematikk',
    medicine: 'Medisin',
    law: 'Juss',
    finance: 'Finans',
    computing: 'Informatikk',
    // Interview subjects
    softwareEngineering: 'Programvareutvikling',
    investmentBanking: 'Investeringsbank',
    medicalResidency: 'Medisinsk spesialisering',
    quantitativeResearcher: 'Kvantitativ forsker',
    managementConsulting: 'Ledelseskonsulent',
    criminalLawyer: 'Strafferettsadvokat',
    electricalEngineer: 'Elektroingeniør',
    productManager: 'Produktleder',
  },
  Danish: {
    skip: 'Spring Over',
    next: 'Næste',
    back: 'Tilbage',
    welcomeTo: 'Velkommen til',
    prepQuest: 'PrepQuest!',
    yourLearningJourney: 'Din læringsrejse begynder her',
    whatAreYouPreppingFor: 'Hvad forbereder du dig på?',
    studyPrep: 'Studie',
    interviewPrep: 'Interview',
    selectLanguage: 'Vælg Sprog',
    great: 'Fantastisk!',
    justAFewMoreQuestions: 'Bare et par spørgsmål mere for at komme i gang...',
    progress: '1/3',
    whichSubjects: 'Hvilke fag forbereder du dig på?',
    // Study subjects
    history: 'Historie',
    physics: 'Fysik',
    chemistry: 'Kemi',
    biology: 'Biologi',
    geography: 'Geografi',
    math: 'Matematik',
    medicine: 'Medicin',
    law: 'Jura',
    finance: 'Finans',
    computing: 'Informatik',
    // Interview subjects
    softwareEngineering: 'Softwareudvikling',
    investmentBanking: 'Investeringsbank',
    medicalResidency: 'Medicinsk specialisering',
    quantitativeResearcher: 'Kvantitativ forsker',
    managementConsulting: 'Ledelseskonsulent',
    criminalLawyer: 'Strafferetsadvokat',
    electricalEngineer: 'Elektroingeniør',
    productManager: 'Produktleder',
  },
};

export const getTranslatedText = (language: string, key: string): string => {
  const lang = stringsOnboarding[language as keyof typeof stringsOnboarding];
  if (!lang) {
    return stringsOnboarding.English[key as keyof typeof stringsOnboarding.English];
  }
  return lang[key as keyof typeof lang] || stringsOnboarding.English[key as keyof typeof stringsOnboarding.English];
};
