export const strings: Record<string, any> = {
  English: {
    // Splash screen strings
    splash: {
      loading: 'Loading...',
      welcomeBack: 'Welcome back!',
      welcomeAboard: 'Welcome Aboard!',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      forgotPassword: 'Forgot Password?',
      orSignInWith: 'Or Sign In With',
      orSignUpWith: 'Or Sign Up With',
      continueWithGoogle: 'Continue with Google',
      continueWithApple: 'Continue with Apple',
      continueWithFacebook: 'Continue with Facebook',
      fillUpBothEmailAndPassword: 'Fill up both email and password',
      passwordsDontMatch: 'Passwords don\'t match',
      accountCreatedSuccessfully: 'Account created successfully!',
      signUpFailed: 'Sign up failed',
      signInFailed: 'Sign in failed',
      providerNotSupported: 'Provider not supported',
      googleSignInFailed: 'Google sign in failed',
      facebookSignInFailed: 'Facebook sign in failed',
      appleSignInFailed: 'Apple sign in failed',
      resetPassword: 'Reset Password',
      resetPasswordSubtitle: 'Enter your email address and we\'ll send you a link to reset your password.',
      enterYourEmail: 'Enter your email',
      cancel: 'Cancel',
      sendEmail: 'Send Email',
      sending: 'Sending...',
      pleaseEnterYourEmailAddress: 'Please enter your email address',
      passwordResetEmailSent: 'Password reset email sent! Check your inbox.',
      failedToSendResetEmail: 'Failed to send reset email',
      // Email verification strings
      verifyEmail: 'Verify Your Email',
      verifyEmailSubtitle: 'We\'ve sent a verification code to your email address. Please enter the code below.',
      enterVerificationCode: 'Enter verification code',
      verify: 'Verify',
      verifying: 'Verifying...',
      resendCode: 'Resend Code',
      resendingCode: 'Resending...',
      verificationCodeSent: 'Verification code sent!',
      verificationFailed: 'Verification failed',
      invalidVerificationCode: 'Invalid verification code',
      pleaseEnterAllDigits: 'Please enter all 6 digits',
      // Password reset flow strings
      verifyYourEmail: 'Verify Your Email',
      firstKeyInCodeToVerify: 'First key in the code sent to your email to verify your email',
      setNewPassword: 'Set New Password',
      enterYourNewPassword: 'Enter your new password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      done: 'Done',
      passwordResetSuccess: 'Your password has been reset! Try logging in',
    },
                    // Statistics page strings
                statistics: {
                  decksFlashcards: 'Decks / Flashcards',
                  performance: 'Performance',
                },
                // ViewDecksInFolder page strings
                viewDecksInFolder: {
                  noDecksInFolder: "Whoops! No more\ndecks in this folder",
                  select: 'Select',
                  selectAll: 'Select All',
                  decksCount: 'Decks',
                  editFolderNamePlaceholder: 'Edit folder name...',
                  folderNameEmpty: 'Folder name cannot be empty!',
                  folderNameExists: 'Folder name already exists!',
                  errorUpdatingFolderName: 'Error updating folder name!',
                  deleteFromFolderConfirmation: 'Are you sure you want to delete from this folder?',
                },
                // ViewFlashcards page strings
                viewFlashcardsPage: {
                  // Column titles
                  topics: 'Topics',
                  qnTypes: 'Qn Types',
                  flashcards: 'Flashcards',
                  select: 'Select',
                  selectAll: 'Select All',
                  // Loading messages
                  loadingTopics: 'Loading topics...',
                  loadingQnTypes: 'Loading question types...',
                  loadingFlashcards: 'Loading flashcards...',
                  // Empty state messages
                  noTopicsSpecified: 'No topics specified',
                  noQuestionTypesFound: 'No question types found',
                  noFlashcardsFound: 'No flashcards found',
                  // Difficulty labels
                  again: 'Again',
                  hard: 'Hard',
                  good: 'Good',
                  easy: 'Easy',
                  none: 'None',
                  // Media placeholders
                  imagePlaceholder: '<Image>',
                  audioPlaceholder: '<Audio>',
                  // Delete confirmation
                  deleteFlashcardsConfirmation: 'Are you sure you want to delete these flashcard(s)?',
                  // Cognitive question type labels
                  cognitiveQnTypes: {
                    recall: 'Recall',
                    application: 'Application',
                    analysis: 'Analysis',
                    synthesis: 'Synthesis',
                    evaluation: 'Evaluation',
                    comprehension: 'Comprehension',
                    problemSolving: 'Problem-Solving',
                    none: 'None',
                  },
                },
    // Index page (Decks screen) strings
    index: {
      myStudyDecks: 'My Study Decks',
      myInterviewDecks: 'My Interview Decks',
      select: 'Select',
      selectAll: 'Select All',
      whereHaveAllTheDecksGone: 'Where have all the\ndecks gone',
      filterDecksBasedOnDateAdded: 'Filter decks based on\ndate added',
    },
    // AddDeckModal strings
    addFlashcardsToDeck: 'Add Flashcard(s) to Deck',
    addDeckToFavorites: 'Add Deck to Favorites',
    addDeckToFolder: 'Add Deck to Folder',
    addDeck: 'Add Deck',
    genAIForm: 'Gen AI Form',
    fileUpload: 'File Upload',
    youtubeLink: 'YouTube Link',
    manual: 'Manual',
    // InterviewStudyToggle strings
    study: 'Study',
    interview: 'Interview',
    // AIDeckCard strings
    cardTypes: {
      behavioral: 'Behavioral',
      technical: 'Technical',
      brainteasers: 'Brainteasers',
      'case study': 'Case Study',
      others: 'Others',
      study: 'Study',
    },
    cards: 'cards',
    // Card component strings
    progress: 'progress',
    completed: 'Completed!',
    untitledDeck: 'Untitled Deck',
    // AIPromptModal strings
    aiPromptTitle: 'Try these AI Decks created just for you!',
    loadingAiDecks: 'Loading AI decks...',
    noDeckSuggestions: 'Oops! No deck',
    noDeckSuggestionsSubtitle: 'suggestions for now',
    emptyStateFooter: 'We\'ll generate more',
    emptyStateFooterSubtitle: 'as you practice more!',
    // FolderCard strings
    decks: 'decks',
    // FormHeaderIcons strings
    clearAll: 'Clear All',
    // KindsOfQuestions strings
    kindsOfQuestionsTitle: '4. What kinds of questions do you want to practice more of? (Pick any)',
    questionTypes: {
      recall: 'Recall',
      comprehension: 'Comprehension',
      application: 'Application',
      analysis: 'Analysis',
      synthesis: 'Synthesis',
      evaluation: 'Evaluation',
      problemSolving: 'Problem-Solving',
    },
    // QuestionTextBarWithDropdown strings
    companiesStartingWith: 'Companies starting with',
    selectACompany: 'Select a company',
    noCompaniesFoundStartingWith: 'No companies found starting with',
    noCompaniesFound: 'No companies found',
    loadingCompanies: 'Loading companies...',
    // TypeOfInterviewQn strings
    typeOfInterviewTitle: '2. Which kind of interview are you preparing for? (Pick One)',
    interviewTypes: {
      technical: 'Technical',
      behavioral: 'Behavioral',
      brainteasers: 'Brainteasers',
      caseStudy: 'Case Study',
      others: 'Others',
    },
    // ActionButtonsRow strings
    cancel: 'Cancel',
    minimize: 'Minimize',
    // BottomTextInputModal strings
    editDeckName: 'Edit deck name',
    done: 'Done',
    // DifficultyToggleRow strings
    difficultyOptions: {
      default: 'Default',
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
    },
    // HeaderIconButtons strings
    searchPlaceholders: {
      decks: 'Search for Decks',
      folders: 'Search for Folders',
      favorites: 'Search Favorites',
      default: 'Search',
    },
    sortOptions: {
      name: 'Name',
      dateAdded: 'Date Added',
      lastModified: 'Last Modified',
    },
    // NavBar strings
    navItems: {
      account: 'Account',
      decks: 'Decks',
      statistics: 'Statistics',
      awards: 'Awards',
      stats: 'Stats',
    },
    // SlidingMenu strings
    viewFolders: 'View Folders',
    // Folders strings
    folders: {
      folders: 'Folders',
      addToFolders: 'Add to Folder(s)',
      moveToFolders: 'Move to Folder(s)',
      foldersCount: 'Folders',
      select: 'Select',
      selectAll: 'Select All',
      done: 'Done',
      whereHaveAllTheFoldersGone: "Where have all the\nfolders gone",
      pleaseChooseAtLeastOneFolder: 'Please choose at least one folder if you want to delete.',
      areYouSureYouWantToDeleteTheseFolders: 'Are you sure you want to delete these folder(s)?',
      filterFoldersBasedOnDateAdded: 'Filter folders based on\ndate added',
    },
    viewFavorites: 'View Favorites',
    // AddViewToggle strings
    addFlashcards: 'Add Flashcard(s)',
    viewFlashcards: 'View Flashcard(s)',
    // DrawableOptionsRow strings
    clear: 'Clear',
    // FlippableCard strings
    typeHere: 'Type here!',
    drawHere: 'Draw here!',
    pressHoldMic: 'Press & hold mic \nbutton to record',
    greatReplay: 'Great! Click the replay\nbutton below to play\nthe recorded audio!',
    clickToTakeOrUpload: 'Click here to take\nyour picture or\nupload from library!',
    chooseManual: 'Choose your manual \noption above',
    cameraPermissionError: 'Sorry, we need camera permissions to make this work!',
    photoLibraryPermissionError: 'Sorry, we need camera roll permissions to make this work!',
    imageSelectionError: 'Error selecting image. Please try again.',
    photoCaptureError: 'Error taking photo. Please try again.',
    // CalendarModal strings
    calendarSubtitle: 'Press "Done" or "Choose Date" to apply your selection.',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    all: 'All',
    chooseDate: 'Choose Date',
    // GenericModal strings
    no: 'No',
    yes: 'Yes',
    ok: 'OK',
    success: 'Success',
    error: 'Error',
    cancelBackup: 'Cancel backup?',
    // TabLayout strings
    deleteDecksConfirmation: 'Are you sure you want to delete these deck(s)?',
    noSelectionMade: 'No selection made!',
    noSelectionSubtitle: 'Please choose at least one deck if you want to delete or add to folder.',
    confirmAddToFolders: 'Confirm adding to\nfolder(s)?',
    confirmMoveToFolders: 'Confirm moving to\nfolder(s)?',
    unfavoriteConfirmation: 'Are you sure you want to unfavorite?',
    customGoalFormSubmitted: ['Custom Goal Form', 'Submitted!'],
    deleteDeckConfirmation: 'Are you sure you want to delete this deck?',
    deckMovedToFolder: ['Deck(s) moved', 'into folder(s)!'],
    aiDeckSavedSuccessfully: ['AI Deck', 'saved successfully!'],
    deckSavedToFolder: ['Deck(s) saved', 'into folder(s)!'],
    deleteFolderConfirmation: 'Are you sure you want to delete this folder?',
    decksAlreadyInFolders: ['One or more decks you', 'have selected are already', 'in the selected folder(s)!'],
    // AverageGradeThermometer strings
    averageGrade: 'Average Grade',
    // AverageSpeedTotal strings
    averageTimePerFlashcard: 'Average time per flashcard',
    seconds: 's',
    // BreakdownByDifficultyPie strings
    breakdownByDifficulty: 'Breakdown of Flashcards by Difficulty',
    noDifficultyData: 'No difficulty data available',
    completeSomeFlashcards: 'Complete some flashcards to see your breakdown',
    difficultyLabels: {
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
    },
    // BreakdownOfDecksFlashcards strings
    breakdownOfDecksFlashcards: 'Breakdown of Number of Decks / Flashcards',
    loading: 'Loading...',
    noDataAvailable: 'No data available',
    breakdownDecks: 'Decks',
    breakdownFlashcards: 'Flashcards',
    breakdownCategoryLabels: {
      study: 'Study',
      technical: 'Technical',
      caseStudy: 'Case study',
      behavioral: 'Behavioral',
      brainteasers: 'Brainteasers',
      others: 'Others',
    },
    // GradeChart strings
    gradeChart: 'Grade Chart (%)',
    day: 'Day',
    month: 'Month',
    loadingGradeData: 'Loading grade data...',
    noGradeDataAvailable: 'No grade data available',
    studyOrQuizToSeeProgress: 'Study or quiz flashcards to see your progress',
    // MoreDetailsStats strings
    moreDetails: 'More Details',
    loadingStatistics: 'Loading statistics...',
    moreDetailsDecks: 'Decks',
    moreDetailsFlashcards: 'Flashcards',
    moreDetailsStudy: 'Study',
    moreDetailsInterview: 'Interview',
    accumulatedDecks: 'Accumulated\nDecks',
    decksInLocalStorage: 'Decks in local\nstorage',
    totalDecksQuizzed: 'Total decks\nquizzed',
    accumulatedFlashcards: 'Accumulated\nFlashcards',
    flashcardsInLocalStorage: 'Flashcards in\nlocal storage',
    totalFlashcardsQuizzed: 'Total Flashcards\nquizzed',
    accumulatedStudyDecks: 'Accumulated\nStudy Decks',
    studyDecksInLocalStorage: 'Study decks in\nlocal storage',
    totalStudyDecksQuizzed: 'Total Study\ndecks quizzed',
    accumulatedInterviewDecks: 'Accumulated\nInterview Decks',
    interviewDecksInLocalStorage: 'Interview decks\nin local storage',
    totalInterviewDecksQuizzed: 'Total Interview\ndecks quizzed',
    // ReviewLineGraph strings
    decksFlashcardsReviewed: 'Decks / Flashcards Reviewed',
    loadingReviewData: 'Loading review data...',
    noReviewDataAvailable: 'No review data available yet. Start studying to see your progress!',
    reviewDay: 'Day',
    reviewMonth: 'Month',
    reviewDecks: 'Decks',
    reviewFlashcards: 'Flashcards',
    // SpeedChart strings
    speedChart: 'Speed Chart (average speed per flashcard)',
    loadingSpeedData: 'Loading speed data...',
    noSpeedDataAvailable: 'No speed data available',
    studyOrQuizToSeeSpeedTrends: 'Study or quiz flashcards to see your speed trends',
    // Account strings
    signOut: 'Sign Out',
    username: 'Username',
    user: 'User',
    userId: 'User ID',
    notAvailable: 'Not available',
    currentPlan: 'Current Plan',
    basicPlan: 'Basic Plan',
    website: 'Website',
    rateAndReview: 'Rate &\nReview',
    share: 'Share',
    termsAndConditions: 'Terms &\nConditions',
    appSettings: 'App\nSettings',
    deckSettings: 'Deck\nSettings',
    upgrade: 'Upgrade',
    currentStats: 'Current Stats',
    genAIFormRequests: 'GenAI Form Requests',
    fileUploadFormRequests: 'File Upload\nForm Requests',
    youtubeLinkFormRequests: 'Youtube Link\nForm Requests',
    aiChatFeedbackRequests: 'AI Chat\nRequests',
    signOutConfirmation: 'Sign Out',
    signOutMessage: 'Are you sure you want to sign out?',
    shareMessage: 'Check out PrepQuest! https://prepquest.app',
    // AppSettings strings
    appSettingsPage: {
      title: 'App Settings',
      language: 'Language',
      languages: {
        english: 'English',
        chinese: '中文',
      },
      cameraAccess: 'Camera Access',
      galleryAccess: 'Gallery Access',
      microphoneAccess: 'Microphone Access',
      notifications: 'Notifications',
      backupDataToCloud: 'Backup data to cloud',
      loadDataFromCloud: 'Load data from cloud',
      clearLocalStorageData: 'Clear local storage data',
      deleteAccount: 'Delete Account?',
      backupDescription: 'Backup your local storage to cloud regularly so that you can access your data on other devices\nand so that AIDecks can be generated based on your latest decks/flashcards.\n\nEach backup will replace the previous one. For more clarification, please refer to the FAQ in our ',
      website: 'website',
      loadDataDescription: 'Import your existing data and progress from cloud if you logging in from another phone.\n\nEach import will replace your existing local storage. For more clarification, please refer to the FAQ in our ',
      clearLocalStorageDescription: 'This will delete all your local storage data and you will not be able to recover it. Please backup your data to cloud before clearing.',
      proceedWithCloudBackup: 'Proceed with\ncloud backup?',
      proceedWithCloudImport: 'Proceed with\ncloud import?',
      proceedWithClearingLocalStorage: 'Proceed with clearing\nlocal storage?',
      cameraPermissionRequired: 'Camera Permission Required',
      cameraPermissionMessage: 'Camera access is required to take photos. Please enable it in your device settings.',
      cameraPermission: 'Camera Permission',
      cameraPermissionDisableMessage: 'To disable camera access, please go to your device settings and disable camera permissions for this app.',
      galleryPermissionRequired: 'Gallery Permission Required',
      galleryPermissionMessage: 'Gallery access is required to upload images. Please enable it in your device settings.',
      galleryPermission: 'Gallery Permission',
      galleryPermissionDisableMessage: 'To disable gallery access, please go to your device settings and disable gallery permissions for this app.',
      microphonePermissionRequired: 'Microphone Permission Required',
      microphonePermissionMessage: 'Microphone access is required to record audio. Please enable it in your device settings.',
      microphonePermission: 'Microphone Permission',
      microphonePermissionDisableMessage: 'To disable microphone access, please go to your device settings and disable microphone permissions for this app.',
      settings: 'Settings',
      backupInProgress: 'Backup in Progress',
    },
    // DeckSettings strings
    deckSettingsPage: {
      title: 'Deck Settings',
      autoDecks: 'Auto-decks',
      autoDecksDescription: 'Turning this on will allow decks to be auto-generated based on your most recent decks created and reviewed.',
      flashcardSettings: 'Flashcard settings',
      clozeQuestions: 'Cloze Questions',
      clozeQuestionsDescription: 'Enabling this will allow questions to be generated and displayed in cloze format to you. This applies mainly to recall-based questions.',
      mcqQuestions: 'MCQ Questions',
      mcqQuestionsDescription: 'Enabling this will allow answers to be generated and displayed in a MCQ format to you. This applies mainly to the following question types:',
      mcqQuestionTypes: [
        'Recall-based questions',
        'Comprehension-based questions', 
        'Analysis-based questions',
      ],
      voiceRecordedAnswers: 'Voice-Recorded Answers',
      voiceRecordedAnswersDescription: 'With this enabled, you can record your answers and get feedback by AI. This applies if you are preparing for Behavioral Interviews and Case Interviews or if you are preparing for these question types:',
      voiceRecordedQuestionTypes: [
        'Application-based questions',
        'Synthesis-based questions', 
        'Evaluation-based questions',
        'Problem-Solving questions',
      ],
      voiceRecordingTimer: 'Voice Recording Timer',
      voiceRecordingTimerDescription: 'Set the time limit for voice recording answers in quiz mode.',
      quizPreferences: 'Quiz Preferences',
      halfwayCheckpoint: 'Halfway Checkpoint',
      halfwayCheckpointDescription: 'Turning this on will let you see current statistics of your quiz performance halfway through the quiz.',
      timerSettingsForDifficulty: 'Timer Settings for Respective Difficulty',
      backToDefaultSettings: 'Back to default settings?',
      helpModalText: "Our team has identified 7 main types of cognitive questions based on Bloom's taxonomy to help with your learning. Visit our website to learn more.",
      helpModalWebsite: 'our website',
      timePicker: {
        min: 'min',
        sec: 'sec',
      },
    },
    // Awards strings
    goals: 'Goals',
    achievements: 'Achievements',
    fillInCustomGoal: 'Fill in your custom goal here!',
    toAchieveGoals: 'To achieve my goals, I pledge to',
    studyDiligently: 'study diligently by studying',
    decksContinuously: 'decks continuously',
    forDays: 'for ',
    daysPeriod: 'days.',
    submit: 'Submit',
    signHere: 'sign here',
    singleFingerStroke: '(single finger stroke)',
    longestStreak: 'Longest Streak',
    days: 'days',
    decksStudied: 'decks\nstudied',
    flashcardsStudied: 'flashcards\nstudied',
    customBadges: 'Custom Badges',
    dailyStreakBadges: 'Daily Streak Badges',
    weeklyStreakBadges: 'Weekly Streak Badges',
    welcomeBadges: 'Welcome Badges',
    lifetimeBadges: 'Lifetime Badges',
    viewAll: 'View All',
    collapse: 'Collapse',
    // DeckDetails strings
    deckDetails: {
      deckNameCannotBeEmpty: 'Deck name cannot be empty!',
      deckNameAlreadyExists: 'Deck name already exists!',
      errorUpdatingDeckName: 'Error updating deck name!',
      noStatsYet: 'No stats yet! View, study or quiz yourself on this deck in the meantime!',
      createdVia: 'Created via',
      subjects: 'Subject(s)',
      topicsSubtopics: 'Topics/Subtopics',
      educationLevel: 'Education Level',
      examQuiz: 'Exam/Quiz',
      lastReviewedDate: 'Last Reviewed date',
      jobRole: 'Job/Role',
      company: 'Company',
      topics: 'Topics',
      experienceLevel: 'Experience Level',
      masteryLevels: {
        expert: 'Expert',
        proficient: 'Proficient',
        developing: 'Developing',
        beginner: 'Beginner',
        needsPractice: 'Needs Practice',
      },
    },
    // Favorites strings
    favorites: {
      favDecks: 'Fav Decks',
      favFolders: 'Fav Folders',
      favoriteDecks: 'Favorite Decks',
      favoriteFolders: 'Favorite Folders',
      select: 'Select',
      selectAll: 'Select All',
      whoopsWhereDidAllYourFavoriteDecksGo: "Whoops! Where did\nall your favorite decks go",
      whoopsWhereDidAllYourFavoriteFoldersGo: "Whoops! Where did\nall your favorite folders go",
      filterFavoritesBasedOnDateAdded: 'Filter favorites based on\ndate added',
      pleaseChooseAtLeastOneFolder: "Please choose at least one folder if you want to delete or unfavorite.",
      pleaseChooseAtLeastOneDeck: "Please choose at least one deck if you want to delete, add to folder or unfavorite.",
      areYouSureYouWantToDeleteTheseFolders: 'Are you sure you want to delete these folder(s)?',
      areYouSureYouWantToDeleteTheseDecks: 'Are you sure you want to delete these deck(s)?',
      areYouSureYouWantToUnfavoriteTheseFolders: 'Are you sure you want to unfavorite these folder(s)?',
      areYouSureYouWantToUnfavoriteTheseDecks: 'Are you sure you want to unfavorite these deck(s)?',
    },
    // FlashcardView page strings
    flashcardViewPage: {
      // Timer and countdown
      timesUp: "Time's Up!",
      seconds: 's',
      // Labels
      question: 'Question',
      answer: 'Answer',
      // Buttons
      submit: 'Submit',
      ok: 'OK',
      // Delete confirmation
      deleteFlashcardConfirmation: 'Are you sure you want to delete this flashcard?',
      // Study/Quiz exit confirmation
      endStudySessionMidway: 'End study session midway?',
      endQuizSessionMidway: 'End quiz session midway?',
      // Difficulty labels
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
      // Loading text
      loading: 'Loading...',
      // Validation messages
      cannotMoveOnWithoutAnswer: 'Cannot move on until you have viewed answer and selected a difficulty!',
      pleaseFlipCardToViewAnswer: 'Please flip the card to view the answer before moving on to the next flashcard!',
      pleaseSelectDifficulty: 'Give this flashcard a difficulty rating before moving onto the next flashcard!',
      cannotMoveOnWithoutMCQ: 'Cannot move on until you have viewed the back, answered the MCQ, and selected a difficulty!',
      pleaseFlipCardToAnswerMCQ: 'Please flip the card to view and answer the MCQ before moving onto the next flashcard!',
      cannotMoveOnWithoutMCQAnswer: 'Cannot move on until you have answered the MCQ and selected a difficulty!',
      pleaseAnswerMCQ: 'Cannot move on until you have answered the MCQ!',
      cannotMoveOnWithoutVoiceAnswer: 'Cannot move on until you have viewed the back, recorded your voice answer, and selected a difficulty!',
      pleaseFlipCardToRecordVoice: 'Please flip the card to view and record your voice answer before moving onto the next flashcard!',
      cannotMoveOnWithoutVoiceRecording: 'Cannot move on until you have recorded your voice answer and selected a difficulty!',
      pleaseRecordVoiceAnswer: 'Cannot move on until you have recorded your voice answer!',
      // Copy to clipboard messages
      copiedTextToClipboard: 'Copied text to clipboard!',
      copiedMCQTextToClipboard: 'Copied MCQ text to clipboard!',
      copiedImageToClipboard: 'Copied image to clipboard!',
      failedToCopyImage: 'Failed to copy image to clipboard',
      failedToCopy: 'Failed to copy to clipboard',
      // Success messages
      nicelyDone: 'Nicely done!',
      niceStudying: 'Nice studying!',
      // Retry messages
      retryDifficultFlashcards: 'Retry difficult flashcards?',
      noDifficultFlashcardsToRetry: 'No difficult flashcards to retry',
      // Navigation labels
      viewQuizStats: 'View Quiz Stats',
      backToDeck: 'Back to Deck',
      // Quiz countdown
      quizStartingIn: 'Quiz starting in...',
      // Question/Answer labels
      questionLabel: 'Qn',
      answerLabel: 'Ans',
      ofLabel: 'of',
      // Voice answer messages
      greatAnswerReplayOrFeedback: 'Great answer! Replay your audio or get feedback by AI!',
      recordAnswerGetFeedback: 'Record your answer and get feedback by AI!',
      // Completion message
      completed: 'Completed!',
      // MCQ feedback messages
      correctAnswerGoodJob: "That's correct! Good job!",
      incorrectAnswerTryAgain: "Oops that's incorrect! Try again next time!",
      // Loading progress message
      flashcardsLoaded: 'Flashcards loaded',
      outOf: 'out of',
      // Quiz stats related
      totalTimeSpent: 'Total time spent:',
      continueWithQuiz: 'Continue with quiz',
      wellDone: 'Well Done!',
      // Deck creation related
      creatingFlashcards: 'Creating Flashcards...',
      creatingDeck: 'Creating Deck...',
      halfwayCheckpoint: 'Halfway\nCheckpoint',
      // Quiz stats progress indicator
      flashcardsCompleted: 'of flashcards completed',
      flashcardsCompletedChinese: '张卡片已完成',
    },
  },
  Chinese: {
    // Splash screen strings
    splash: {
      loading: '加载中...',
      welcomeBack: '欢迎回来！',
      welcomeAboard: '欢迎加入！',
      email: '邮箱',
      password: '密码',
      confirmPassword: '确认密码',
      signIn: '登录',
      signUp: '注册',
      forgotPassword: '忘记密码？',
      orSignInWith: '或使用以下方式登录',
      orSignUpWith: '或使用以下方式注册',
      continueWithGoogle: '使用 Google 继续',
      continueWithApple: '使用 Apple 继续',
      continueWithFacebook: '使用 Facebook 继续',
      fillUpBothEmailAndPassword: '请填写邮箱和密码',
      passwordsDontMatch: '密码不匹配',
      accountCreatedSuccessfully: '账户创建成功！',
      signUpFailed: '注册失败',
      signInFailed: '登录失败',
      providerNotSupported: '不支持的提供商',
      googleSignInFailed: 'Google 登录失败',
      facebookSignInFailed: 'Facebook 登录失败',
      appleSignInFailed: 'Apple 登录失败',
      resetPassword: '重置密码',
      resetPasswordSubtitle: '输入您的邮箱地址，我们将发送重置密码链接给您。',
      enterYourEmail: '输入您的邮箱',
      cancel: '取消',
      minimize: '最小化',
      sendEmail: '发送邮件',
      sending: '发送中...',
      pleaseEnterYourEmailAddress: '请输入您的邮箱地址',
      passwordResetEmailSent: '密码重置邮件已发送！请检查您的收件箱。',
      failedToSendResetEmail: '发送重置邮件失败',
    },
                    // Statistics page strings
                statistics: {
                  decksFlashcards: '卡片组 / 卡片',
                  performance: '表现',
                },
                // ViewDecksInFolder page strings
                viewDecksInFolder: {
                  noDecksInFolder: '此文件夹中没有卡组',
                  select: '选择',
                  selectAll: '全选',
                  decksCount: '卡组',
                  editFolderNamePlaceholder: '编辑文件夹名称...',
                  folderNameEmpty: '文件夹名称不能为空！',
                  folderNameExists: '文件夹名称已存在！',
                  errorUpdatingFolderName: '更新文件夹名称时出错！',
                  deleteFromFolderConfirmation: '确定要从此文件夹中删除吗？',
                },
                // ViewFlashcards page strings
                viewFlashcardsPage: {
                  // Column titles
                  topics: '主题',
                  qnTypes: '题型',
                  flashcards: '卡片',
                  select: '选择',
                  selectAll: '全选',
                  // Loading messages
                  loadingTopics: '正在加载主题...',
                  loadingQnTypes: '正在加载题型...',
                  loadingFlashcards: '正在加载卡片...',
                  // Empty state messages
                  noTopicsSpecified: '未指定主题',
                  noQuestionTypesFound: '未找到题型',
                  noFlashcardsFound: '未找到卡片',
                  // Difficulty labels
                  again: '重来',
                  hard: '困难',
                  good: '良好',
                  easy: '简单',
                  none: '无',
                  // Media placeholders
                  imagePlaceholder: '<图片>',
                  audioPlaceholder: '<音频>',
                  // Delete confirmation
                  deleteFlashcardsConfirmation: '确定要删除这些卡片吗？',
                  // Cognitive question type labels
                  cognitiveQnTypes: {
                    recall: '回忆',
                    application: '应用',
                    analysis: '分析',
                    synthesis: '综合',
                    evaluation: '评估',
                    comprehension: '理解',
                    problemSolving: '解决',
                    none: '无',
                  },
                },
    // Index page (Decks screen) strings
    index: {
      myStudyDecks: '我的学习卡片组',
      myInterviewDecks: '我的面试卡片组',
      select: '选择',
      selectAll: '全选',
      whereHaveAllTheDecksGone: '所有卡片组都去哪了？',
      filterDecksBasedOnDateAdded: '按添加日期筛选卡片组',
    },
    // AddDeckModal strings
    addFlashcardsToDeck: '添加卡片到卡片组',
    addDeckToFavorites: '添加卡片组到收藏夹',
    addDeckToFolder: '添加卡片组到文件夹',
    addDeck: '添加卡片组',
    genAIForm: 'AI 生成表单',
    fileUpload: '文件上传',
    youtubeLink: 'YouTube 链接',
    manual: '手动添加',
    // InterviewStudyToggle strings
    study: '学习',
    interview: '面试',
    // AIDeckCard strings
    cardTypes: {
      behavioral: '行为面试',
      technical: '技术面试',
      brainteasers: '脑筋急转弯',
      'case study': '案例分析',
      others: '其他',
      study: '学习',
    },
    cards: '张卡片',
    // Card component strings
    progress: '进度',
    completed: '已完成！',
    untitledDeck: '未命名卡片组',
    // FlashcardView page strings
    flashcardViewPage: {
      // Timer and countdown
      timesUp: '时间到!',
      seconds: '秒',
      // Labels
      question: '问题',
      answer: '答案',
      // Buttons
      submit: '提交',
      ok: '好的',
      // Delete confirmation
      deleteFlashcardConfirmation: '确定要删除这张卡片吗?',
      // Study/Quiz exit confirmation
      endStudySessionMidway: '中途退出学习?',
      endQuizSessionMidway: '中途退出测验?',
      // Difficulty labels
      again: '重来',
      hard: '困难',
      good: '良好',
      easy: '简单',
      // Loading text
      loading: '加载中...',
      // Validation messages
      cannotMoveOnWithoutAnswer: '请先查看答案并选择难度后再继续!',
      pleaseFlipCardToViewAnswer: '请翻转卡片查看答案后再继续!',
      pleaseSelectDifficulty: '请为此卡片选择一个难度等级后再继续!',
      cannotMoveOnWithoutMCQ: '请先查看背面、回答选择题并选择难度后再继续!',
      pleaseFlipCardToAnswerMCQ: '请翻转卡片并回答选择题后再继续!',
      cannotMoveOnWithoutMCQAnswer: '请先回答选择题并选择难度后再继续!',
      pleaseAnswerMCQ: '请先回答选择题后再继续!',
      cannotMoveOnWithoutVoiceAnswer: '请先查看背面、录音作答并选择难度后再继续!',
      pleaseFlipCardToRecordVoice: '请翻转卡片并录音作答后再继续!',
      cannotMoveOnWithoutVoiceRecording: '请先录音作答并选择难度后再继续!',
      pleaseRecordVoiceAnswer: '请先录音作答后再继续!',
      // Copy to clipboard messages
      copiedTextToClipboard: '已复制到剪贴板!',
      copiedMCQTextToClipboard: '已复制到剪贴板!',
      copiedImageToClipboard: '已复制到剪贴板!',
      failedToCopyImage: '复制失败!',
      failedToCopy: '复制失败!',
      // Success messages
      nicelyDone: '干得漂亮!',
      niceStudying: '学习得不错!',
      // Retry messages
      retryDifficultFlashcards: '重做难题',
      noDifficultFlashcardsToRetry: '没有难题可重做',
      // Navigation labels
      viewQuizStats: '查看测验统计',
      backToDeck: '返回卡组',
      // Quiz countdown
      quizStartingIn: '测验即将开始...',
      // Question/Answer labels
      questionLabel: '题',
      answerLabel: '答',
      ofLabel: '共',
      // Voice answer messages
      greatAnswerReplayOrFeedback: '回答得很好！重放你的音频或通过AI获取反馈!',
      recordAnswerGetFeedback: '录音答题，获取AI反馈!',
      // Completion message
      completed: '已完成！',
      // MCQ feedback messages
      correctAnswerGoodJob: "回答正确! 干得漂亮!",
      incorrectAnswerTryAgain: "回答错误! 下次再试!",
      // Loading progress message
      flashcardsLoaded: '张卡片已加载',
      outOf: '/',
      // Quiz stats related
      totalTimeSpent: '总用时:',
      continueWithQuiz: '继续测验',
      wellDone: '干得漂亮!',
      // Deck creation related
      creatingFlashcards: '正在创建卡片…',
      creatingDeck: '正在创建卡组…',
      halfwayCheckpoint: '中途\n检查点',
      // Quiz stats progress indicator
      flashcardsCompleted: '张卡片已完成',
      flashcardsCompletedChinese: '张卡片已完成',
    },
    // AIPromptModal strings
    aiPromptTitle: '试试为你量身定制的AI卡片组！',
    loadingAiDecks: '正在加载AI卡片组...',
    noDeckSuggestions: '哎呀！',
    noDeckSuggestionsSubtitle: '暂无推荐卡片组',
    emptyStateFooter: '随着你的练习',
    emptyStateFooterSubtitle: '我们会生成更多推荐！',
    // FolderCard strings
    decks: '张卡片',
    // FormHeaderIcons strings
    clearAll: '清空',
    // KindsOfQuestions strings
    kindsOfQuestionsTitle: '4. 你想多练习哪些类型的问题？（可多选）',
    questionTypes: {
      recall: '回忆问题',
      comprehension: '理解问题',
      application: '应用问题',
      analysis: '分析问题',
      synthesis: '综合问题',
      evaluation: '评估问题',
      problemSolving: '解决问题',
    },
    // QuestionTextBarWithDropdown strings
    companiesStartingWith: '以',
    selectACompany: '选择一个公司',
    noCompaniesFoundStartingWith: '没有以',
    noCompaniesFound: '没有公司',
    loadingCompanies: '正在加载公司...',
    // TypeOfInterviewQn strings
    typeOfInterviewTitle: '2. 你正在准备哪种面试？（选一）',
    interviewTypes: {
      technical: '技术',
      behavioral: '行为',
      brainteasers: '脑筋急转弯',
      caseStudy: '案例分析',
      others: '其他',
    },
    // ActionButtonsRow strings
    cancel: '取消',
    minimize: '最小化',
    // BottomTextInputModal strings
    editDeckName: '编辑卡组名称',
    done: '完成',
    // DifficultyToggleRow strings
    difficultyOptions: {
      default: '默认',
      again: '重来',
      hard: '困难',
      good: '良好',
      easy: '简单',
    },
    // HeaderIconButtons strings
    searchPlaceholders: {
      decks: '搜索卡片组',
      folders: '搜索文件夹',
      favorites: '搜索收藏',
      default: '搜索',
    },
    sortOptions: {
      name: '名称',
      dateAdded: '添加日期',
      lastModified: '最近修改',
    },
    // NavBar strings
    navItems: {
      account: '账户',
      decks: '卡片组',
      statistics: '统计',
      awards: '奖项',
      stats: '统计',
    },
    // SlidingMenu strings
    viewFolders: '查看文件夹',
    // Folders strings
    folders: {
      folders: '文件夹',
      addToFolders: '添加到文件夹',
      moveToFolders: '移动到文件夹',
      foldersCount: '文件夹',
      select: '选择',
      selectAll: '全选',
      done: '完成',
      whereHaveAllTheFoldersGone: '所有文件夹都去哪了？',
      pleaseChooseAtLeastOneFolder: '如果要删除，请至少选择一个文件夹。',
      areYouSureYouWantToDeleteTheseFolders: '你确定要删除这些文件夹吗？',
      filterFoldersBasedOnDateAdded: '按添加日期筛选文件夹',
    },
    // SlidingMenu strings
    viewFavorites: '查看收藏',
    // AddViewToggle strings
    addFlashcards: '添加卡片',
    viewFlashcards: '查看卡片',
    // DrawableOptionsRow strings
    clear: '清除',
    // FlippableCard strings
    typeHere: '请在此输入！',
    drawHere: '请在此绘图！',
    pressHoldMic: '按住麦克风按钮录音',
    greatReplay: '太棒了！点击下方按钮播放录音',
    clickToTakeOrUpload: '点击此处拍照或上传图片',
    chooseManual: '请选择上方的手动选项',
    cameraPermissionError: '抱歉，我们需要相机权限才能使用此功能！',
    photoLibraryPermissionError: '抱歉，我们需要相册权限才能使用此功能！',
    imageSelectionError: '选择图片时出错，请重试。',
    photoCaptureError: '拍照时出错，请重试。',
    // CalendarModal strings
    calendarSubtitle: '点击"确定"或"选择日期"应用您的选择。',
    today: '今天',
    thisWeek: '本周',
    thisMonth: '本月',
    all: '全部',
    chooseDate: '选择日期',
    // GenericModal strings
    no: '否',
    yes: '是',
    ok: '确定',
    success: '成功',
    error: '错误',
    cancelBackup: '取消备份？',
    // TabLayout strings
    deleteDecksConfirmation: '你确定要删除这些卡片组吗？',
    noSelectionMade: '未选择任何内容！',
    noSelectionSubtitle: '如果你想删除或添加到文件夹，请至少选择一个卡片组。',
    confirmAddToFolders: '确认添加到文件夹？',
    confirmMoveToFolders: '确认移动到文件夹？',
    unfavoriteConfirmation: '你确定要取消收藏吗？',
    customGoalFormSubmitted: ['自定义目标表单', '已提交！'],
    deleteDeckConfirmation: '你确定要删除这个卡片组吗？',
    deckMovedToFolder: ['卡片组已移动', '到文件夹！'],
    aiDeckSavedSuccessfully: ['AI卡片组', '保存成功！'],
    deckSavedToFolder: ['卡片组已保存', '到文件夹！'],
    deleteFolderConfirmation: '你确定要删除这个文件夹吗？',
    decksAlreadyInFolders: ['你选择的一个或多个卡片组', '已在所选文件夹中！'],
    // AverageGradeThermometer strings
    averageGrade: '平均分数',
    // AverageSpeedTotal strings
    averageTimePerFlashcard: '平均每张卡片用时',
    seconds: '秒',
    // BreakdownByDifficultyPie strings
    breakdownByDifficulty: '按难度分布的卡片',
    noDifficultyData: '暂无难度数据',
    completeSomeFlashcards: '完成一些卡片以查看分布',
    difficultyLabels: {
      again: '再来',
      hard: '困难',
      good: '良好',
      easy: '简单',
    },
    // BreakdownOfDecksFlashcards strings
    breakdownOfDecksFlashcards: '卡组 / 卡片数量分析',
    loading: '正在加载...',
    noDataAvailable: '暂无数据',
    breakdownDecks: '卡组',
    breakdownFlashcards: '卡片',
    breakdownCategoryLabels: {
      study: '学习',
      technical: '技术',
      caseStudy: '案例分析',
      behavioral: '行为',
      brainteasers: '脑筋急转弯',
      others: '其他',
    },
    // GradeChart strings
    gradeChart: '分数图表 (%)',
    day: '日',
    month: '月',
    loadingGradeData: '正在加载分数数据...',
    noGradeDataAvailable: '暂无分数数据',
    studyOrQuizToSeeProgress: '完成一些卡片以查看分布',
    // MoreDetailsStats strings
    moreDetails: '更多详情',
    loadingStatistics: '正在加载统计...',
    moreDetailsDecks: '卡组',
    moreDetailsFlashcards: '卡片',
    moreDetailsStudy: '学习',
    moreDetailsInterview: '面试',
    accumulatedDecks: '累计\n卡组',
    decksInLocalStorage: '本地\n存储卡组',
    totalDecksQuizzed: '已测\n卡组总数',
    accumulatedFlashcards: '累计\n卡片',
    flashcardsInLocalStorage: '本地\n存储卡片',
    totalFlashcardsQuizzed: '已测\n卡片总数',
    accumulatedStudyDecks: '累计\n学习卡组',
    studyDecksInLocalStorage: '本地\n存储学习卡组',
    totalStudyDecksQuizzed: '已测\n学习卡组总数',
    accumulatedInterviewDecks: '累计\n面试卡组',
    interviewDecksInLocalStorage: '本地\n存储面试卡组',
    totalInterviewDecksQuizzed: '已测\n面试卡组总数',
    // ReviewLineGraph strings
    decksFlashcardsReviewed: '已复习卡组 / 卡片',
    loadingReviewData: '正在加载复习数据...',
    noReviewDataAvailable: '暂无复习数据，开始学习以查看进度！',
    reviewDay: '日',
    reviewMonth: '月',
    reviewDecks: '卡组',
    reviewFlashcards: '卡片',
    // SpeedChart strings
    speedChart: '速度图表（每张卡片的平均速度）',
    loadingSpeedData: '正在加载速度数据...',
    noSpeedDataAvailable: '暂无速度数据',
    studyOrQuizToSeeSpeedTrends: '学习或测验卡片以查看速度趋势',
    // Account strings
    signOut: '退出登录',
    username: '用户名',
    user: '用户',
    userId: '用户ID',
    notAvailable: '不可用',
    currentPlan: '当前订阅计划',
    basicPlan: '基础版',
    website: '官网',
    rateAndReview: '评分\n与评价',
    share: '分享',
    termsAndConditions: '条款\n与协议',
    appSettings: '应用\n设置',
    deckSettings: '卡片组\n设置',
    upgrade: '升级',
    currentStats: '当前统计',
    genAIFormRequests: 'AI生成表单请求',
    fileUploadFormRequests: '文件上传表单请求',
    youtubeLinkFormRequests: 'YouTube链接表单请求',
    aiChatFeedbackRequests: 'AI聊天反馈请求',
    signOutConfirmation: '退出登录',
    signOutMessage: '你确定要退出登录吗？',
    shareMessage: '看看 PrepQuest！https://prepquest.app',
    // DeckSettings strings
    deckSettingsPage: {
      title: '卡片组设置',
      autoDecks: '自动创建卡片组',
      autoDecksDescription: '开启此功能后，系统将根据您最近创建和复习的卡片组自动生成新卡片组。',
      flashcardSettings: '闪卡设置',
      clozeQuestions: '填空题',
      clozeQuestionsDescription: '启用后，系统将以填空题形式生成并显示问题，主要适用于回忆类问题。',
      mcqQuestions: '选择题',
      mcqQuestionsDescription: '启用后，系统将以选择题格式生成并显示答案，主要适用于以下题型：',
      mcqQuestionTypes: [
        '回忆类问题 (Recall questions)',
        '理解类问题 (Comprehension questions)',
        '分析类问题 (Analysis questions)',
      ],
      voiceRecordedAnswers: '语音回答',
      voiceRecordedAnswersDescription: '启用此功能后，您可以通过录音回答问题并获得AI反馈。此功能适用于行为面试（Behavioral Interviews）和案例面试（Case Interviews）的准备，或以下题型的练习：',
      voiceRecordedQuestionTypes: [
        '应用类问题 (Application questions)',
        '综合类问题 (Synthesis questions)',
        '评估类问题 (Evaluation questions)',
        '解决问题类问题 (Problem-Solving)',
      ],
      voiceRecordingTimer: '语音录制计时器',
      voiceRecordingTimerDescription: '设置答题时语音录制的时间限制。',
      quizPreferences: '测验偏好',
      halfwayCheckpoint: '中途检查点',
      halfwayCheckpointDescription: '开启此功能后，您将在答题中途看到当前测验表现的统计数据。',
      timerSettingsForDifficulty: '各难度级别的计时设置',
      backToDefaultSettings: '恢复默认设置？',
      helpModalText: '我们的团队基于布鲁姆分类法，确定了7种主要认知题型，助力高效学习。了解更多内容，请访问我们的官网。',
      helpModalWebsite: '官网',
      timePicker: {
        min: '分',
        sec: '秒',
      },
    },
    // AppSettings strings
    appSettingsPage: {
      title: '应用设置',
      language: '语言',
      languages: {
        english: 'English',
        chinese: '中文',
      },
      cameraAccess: '允许访问相机',
      galleryAccess: '允许访问相册',
      microphoneAccess: '允许访问麦克风',
      notifications: '允许发送通知',
      backupDataToCloud: '备份数据到云端',
      loadDataFromCloud: '导入云端备份',
      clearLocalStorageData: '删除本地文件',
      deleteAccount: '删除账户',
      backupDescription: '请定期将本地存储备份至云端，以便在其他设备上访问数据。\n\n每次备份将覆盖之前的记录。如需进一步了解，请参考',
      website: '官网FAQ',
      loadDataDescription: '若从其他手机登录，可从云端导入现有数据和进度。\n\n每次导入将覆盖本地现有存储。如需进一步了解，请参阅',
      clearLocalStorageDescription: '此操作将删除所有本地存储数据且无法恢复。请在清除前将数据备份至云端。',
      proceedWithCloudBackup: '继续云端备份？',
      proceedWithCloudImport: '继续云端导入？',
      proceedWithClearingLocalStorage: '继续清除本地存储？',
      cameraPermissionRequired: '需要相机权限',
      cameraPermissionMessage: '需要相机权限才能拍照。请在设备设置中启用。',
      cameraPermission: '相机权限',
      cameraPermissionDisableMessage: '要禁用相机访问，请前往设备设置并禁用此应用的相机权限。',
      galleryPermissionRequired: '需要相册权限',
      galleryPermissionMessage: '需要相册权限才能上传图片。请在设备设置中启用。',
      galleryPermission: '相册权限',
      galleryPermissionDisableMessage: '要禁用相册访问，请前往设备设置并禁用此应用的相册权限。',
      microphonePermissionRequired: '需要麦克风权限',
      microphonePermissionMessage: '需要麦克风权限才能录音。请在设备设置中启用。',
      microphonePermission: '麦克风权限',
      microphonePermissionDisableMessage: '要禁用麦克风访问，请前往设备设置并禁用此应用的麦克风权限。',
      settings: '设置',
      backupInProgress: '备份进行中',
    },
    // Awards strings
    goals: '目标',
    achievements: '成就',
    fillInCustomGoal: '在这里填写你\n的自定义目标!',
    toAchieveGoals: '为了实现我的目标，我承诺',
    studyDiligently: '努力学习，通过学习',
    decksContinuously: '天连续的卡组',
    forDays: '持续',
    daysPeriod: '天。',
    submit: '提交',
    signHere: 'sign here',
    singleFingerStroke: '（单指签名）',
    longestStreak: '最长连续天数',
    days: '天',
    decksStudied: '已学习\n卡片组',
    flashcardsStudied: '已学习\n卡片',
    customBadges: '自定义徽章',
    dailyStreakBadges: '每日连续天数徽章',
    weeklyStreakBadges: '每周连续天数徽章',
    welcomeBadges: '欢迎徽章',
    lifetimeBadges: '终身徽章',
    viewAll: '查看所有',
    collapse: '收起',
    // DeckDetails strings
    deckDetails: {
      deckNameCannotBeEmpty: '卡片组名称不能为空！',
      deckNameAlreadyExists: '卡片组名称已存在！',
      errorUpdatingDeckName: '更新卡片组名称时出错！',
      noStatsYet: '暂无统计数据！你可以先浏览、学习或测验此卡组。',
      createdVia: '创建方式',
      subjects: '科目',
      topicsSubtopics: '主题/子主题',
      educationLevel: '教育水平',
      examQuiz: '考试/测验',
      lastReviewedDate: '上次复习日期',
      jobRole: '职位',
      company: '公司',
      topics: '主题',
      experienceLevel: '经验水平',
      masteryLevels: {
        expert: '专家',
        proficient: '熟练',
        developing: '发展中',
        beginner: '初学者',
        needsPractice: '需要练习',
      },
    },
    // Favorites strings
    favorites: {
      favDecks: '收藏卡片组',
      favFolders: '收藏文件夹',
      favoriteDecks: '收藏卡片组',
      favoriteFolders: '收藏文件夹',
      select: '选择',
      selectAll: '全选',
      whoopsWhereDidAllYourFavoriteDecksGo: '哎呀！你所有收藏的卡片组都去哪了？',
      whoopsWhereDidAllYourFavoriteFoldersGo: '哎呀！你所有收藏的文件夹都去哪了？',
      filterFavoritesBasedOnDateAdded: '按添加日期筛选收藏',
      pleaseChooseAtLeastOneFolder: "请至少选择一个文件夹，如果你想删除或取消收藏。",
      pleaseChooseAtLeastOneDeck: "请至少选择一个卡片组，如果你想删除、添加到文件夹或取消收藏。",
      areYouSureYouWantToDeleteTheseFolders: '你确定要删除这些文件夹吗？',
      areYouSureYouWantToDeleteTheseDecks: '你确定要删除这些卡片组吗？',
      areYouSureYouWantToUnfavoriteTheseFolders: '你确定要取消收藏这些文件夹吗？',
      areYouSureYouWantToUnfavoriteTheseDecks: '你确定要取消收藏这些卡片组吗？',
    },
  },
};
