export const strings: Record<string, any> = {
  English: {
    // Statistics page strings
    statistics: {
      decksFlashcards: 'Decks / Flashcards',
      performance: 'Performance',
    },
    // Index page (Decks screen) strings
    index: {
      myStudyDecks: 'My Study Decks',
      myInterviewDecks: 'My Interview Decks',
      select: 'Select',
      selectAll: 'Select All',
      whereHaveAllTheDecksGone: 'Where have all the\ndecks gone',
      filterDecksBasedOnDateAdded: 'Filter decks based on\ndate added',
    },
    // AddDeckModal strings
    addFlashcardsToDeck: 'Add Flashcard(s) to Deck',
    addDeckToFavorites: 'Add Deck to Favorites',
    addDeckToFolder: 'Add Deck to Folder',
    addDeck: 'Add Deck',
    genAIForm: 'Gen AI Form',
    fileUpload: 'File Upload',
    youtubeLink: 'YouTube Link',
    manual: 'Manual',
    // InterviewStudyToggle strings
    study: 'Study',
    interview: 'Interview',
    // AIDeckCard strings
    cardTypes: {
      behavioral: 'Behavioral',
      technical: 'Technical',
      brainteasers: 'Brainteasers',
      'case study': 'Case Study',
      others: 'Others',
      study: 'Study',
    },
    cards: 'cards',
    // Card component strings
    progress: 'progress',
    completed: 'Completed!',
    untitledDeck: 'Untitled Deck',
    // AIPromptModal strings
    aiPromptTitle: 'Try these AI Decks created just for you!',
    loadingAiDecks: 'Loading AI decks...',
    noDeckSuggestions: 'Oops! No deck',
    noDeckSuggestionsSubtitle: 'suggestions for now',
    emptyStateFooter: 'We\'ll generate more',
    emptyStateFooterSubtitle: 'as you practice more!',
    // FolderCard strings
    decks: 'decks',
    // FormHeaderIcons strings
    clearAll: 'Clear All',
    // KindsOfQuestions strings
    kindsOfQuestionsTitle: '4. What kinds of questions do you want to practice more of? (Pick any)',
    questionTypes: {
      recall: 'Recall',
      comprehension: 'Comprehension',
      application: 'Application',
      analysis: 'Analysis',
      synthesis: 'Synthesis',
      evaluation: 'Evaluation',
      problemSolving: 'Problem-Solving',
    },
    // QuestionTextBarWithDropdown strings
    companiesStartingWith: 'Companies starting with',
    selectACompany: 'Select a company',
    noCompaniesFoundStartingWith: 'No companies found starting with',
    noCompaniesFound: 'No companies found',
    loadingCompanies: 'Loading companies...',
    // TypeOfInterviewQn strings
    typeOfInterviewTitle: '2. Which kind of interview are you preparing for? (Pick One)',
    interviewTypes: {
      technical: 'Technical',
      behavioral: 'Behavioral',
      brainteasers: 'Brainteasers',
      caseStudy: 'Case Study',
      others: 'Others',
    },
    // ActionButtonsRow strings
    cancel: 'Cancel',
    // BottomTextInputModal strings
    editDeckName: 'Edit deck name',
    done: 'Done',
    // DifficultyToggleRow strings
    difficultyOptions: {
      default: 'Default',
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
    },
    // HeaderIconButtons strings
    searchPlaceholders: {
      decks: 'Search for Decks',
      folders: 'Search for Folders',
      favorites: 'Search Favorites',
      default: 'Search',
    },
    sortOptions: {
      name: 'Name',
      dateAdded: 'Date Added',
      lastModified: 'Last Modified',
    },
    // NavBar strings
    navItems: {
      account: 'Account',
      decks: 'Decks',
      statistics: 'Statistics',
      awards: 'Awards',
      stats: 'Stats',
    },
    // SlidingMenu strings
    viewFolders: 'View Folders',
    // Folders strings
    folders: {
      folders: 'Folders',
      addToFolders: 'Add to Folder(s)',
      moveToFolders: 'Move to Folder(s)',
      foldersCount: 'Folders',
      select: 'Select',
      selectAll: 'Select All',
      done: 'Done',
      whereHaveAllTheFoldersGone: "Where have all the\nfolders gone",
      pleaseChooseAtLeastOneFolder: 'Please choose at least one folder if you want to delete.',
      areYouSureYouWantToDeleteTheseFolders: 'Are you sure you want to delete these folder(s)?',
      filterFoldersBasedOnDateAdded: 'Filter folders based on\ndate added',
    },
    viewFavorites: 'View Favorites',
    // AddViewToggle strings
    addFlashcards: 'Add Flashcard(s)',
    viewFlashcards: 'View Flashcard(s)',
    // DrawableOptionsRow strings
    clear: 'Clear',
    // FlippableCard strings
    typeHere: 'Type here!',
    drawHere: 'Draw here!',
    pressHoldMic: 'Press & hold mic \nbutton to record',
    greatReplay: 'Great! Click the replay\nbutton below to play\nthe recorded audio!',
    clickToTakeOrUpload: 'Click here to take\nyour picture or\nupload from library!',
    chooseManual: 'Choose your manual \noption above',
    cameraPermissionError: 'Sorry, we need camera permissions to make this work!',
    photoLibraryPermissionError: 'Sorry, we need camera roll permissions to make this work!',
    imageSelectionError: 'Error selecting image. Please try again.',
    photoCaptureError: 'Error taking photo. Please try again.',
    // CalendarModal strings
    calendarSubtitle: 'Press "Done" or "Choose Date" to apply your selection.',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    all: 'All',
    chooseDate: 'Choose Date',
    // GenericModal strings
    no: 'No',
    yes: 'Yes',
    ok: 'OK',
    // TabLayout strings
    deleteDecksConfirmation: 'Are you sure you want to delete these deck(s)?',
    noSelectionMade: 'No selection made!',
    noSelectionSubtitle: 'Please choose at least one deck if you want to delete or add to folder.',
    confirmAddToFolders: 'Confirm adding to\nfolder(s)?',
    confirmMoveToFolders: 'Confirm moving to\nfolder(s)?',
    unfavoriteConfirmation: 'Are you sure you want to unfavorite?',
    customGoalFormSubmitted: ['Custom Goal Form', 'Submitted!'],
    deleteDeckConfirmation: 'Are you sure you want to delete this deck?',
    deckMovedToFolder: ['Deck(s) moved', 'into folder(s)!'],
    aiDeckSavedSuccessfully: ['AI Deck', 'saved successfully!'],
    deckSavedToFolder: ['Deck(s) saved', 'into folder(s)!'],
    deleteFolderConfirmation: 'Are you sure you want to delete this folder?',
    decksAlreadyInFolders: ['One or more decks you', 'have selected are already', 'in the selected folder(s)!'],
    // AverageGradeThermometer strings
    averageGrade: 'Average Grade',
    // AverageSpeedTotal strings
    averageTimePerFlashcard: 'Average time per flashcard',
    seconds: 's',
    // BreakdownByDifficultyPie strings
    breakdownByDifficulty: 'Breakdown of Flashcards by Difficulty',
    noDifficultyData: 'No difficulty data available',
    completeSomeFlashcards: 'Complete some flashcards to see your breakdown',
    difficultyLabels: {
      again: 'Again',
      hard: 'Hard',
      good: 'Good',
      easy: 'Easy',
    },
    // BreakdownOfDecksFlashcards strings
    breakdownOfDecksFlashcards: 'Breakdown of Number of Decks / Flashcards',
    loading: 'Loading...',
    noDataAvailable: 'No data available',
    breakdownDecks: 'Decks',
    breakdownFlashcards: 'Flashcards',
    breakdownCategoryLabels: {
      study: 'Study',
      technical: 'Technical',
      caseStudy: 'Case study',
      behavioral: 'Behavioral',
      brainteasers: 'Brainteasers',
      others: 'Others',
    },
    // GradeChart strings
    gradeChart: 'Grade Chart (%)',
    day: 'Day',
    month: 'Month',
    loadingGradeData: 'Loading grade data...',
    noGradeDataAvailable: 'No grade data available',
    studyOrQuizToSeeProgress: 'Study or quiz flashcards to see your progress',
    // MoreDetailsStats strings
    moreDetails: 'More Details',
    loadingStatistics: 'Loading statistics...',
    moreDetailsDecks: 'Decks',
    moreDetailsFlashcards: 'Flashcards',
    moreDetailsStudy: 'Study',
    moreDetailsInterview: 'Interview',
    accumulatedDecks: 'Accumulated\nDecks',
    decksInLocalStorage: 'Decks in local\nstorage',
    totalDecksQuizzed: 'Total decks\nquizzed',
    accumulatedFlashcards: 'Accumulated\nFlashcards',
    flashcardsInLocalStorage: 'Flashcards in\nlocal storage',
    totalFlashcardsQuizzed: 'Total Flashcards\nquizzed',
    accumulatedStudyDecks: 'Accumulated\nStudy Decks',
    studyDecksInLocalStorage: 'Study decks in\nlocal storage',
    totalStudyDecksQuizzed: 'Total Study\ndecks quizzed',
    accumulatedInterviewDecks: 'Accumulated\nInterview Decks',
    interviewDecksInLocalStorage: 'Interview decks\nin local storage',
    totalInterviewDecksQuizzed: 'Total Interview\ndecks quizzed',
    // ReviewLineGraph strings
    decksFlashcardsReviewed: 'Decks / Flashcards Reviewed',
    loadingReviewData: 'Loading review data...',
    noReviewDataAvailable: 'No review data available yet. Start studying to see your progress!',
    reviewDay: 'Day',
    reviewMonth: 'Month',
    reviewDecks: 'Decks',
    reviewFlashcards: 'Flashcards',
    // SpeedChart strings
    speedChart: 'Speed Chart (average speed per flashcard)',
    loadingSpeedData: 'Loading speed data...',
    noSpeedDataAvailable: 'No speed data available',
    studyOrQuizToSeeSpeedTrends: 'Study or quiz flashcards to see your speed trends',
    // Account strings
    signOut: 'Sign Out',
    username: 'Username',
    user: 'User',
    userId: 'User ID',
    notAvailable: 'Not available',
    currentPlan: 'Current Plan',
    basicPlan: 'Basic Plan',
    website: 'Website',
    rateAndReview: 'Rate &\nReview',
    share: 'Share',
    termsAndConditions: 'Terms &\nConditions',
    appSettings: 'App\nSettings',
    deckSettings: 'Deck\nSettings',
    upgrade: 'Upgrade',
    signOutConfirmation: 'Sign Out',
    signOutMessage: 'Are you sure you want to sign out?',
    shareMessage: 'Check out PrepQuest! https://prepquest.app',
    // Awards strings
    goals: 'Goals',
    achievements: 'Achievements',
    fillInCustomGoal: 'Fill in your custom goal here!',
    toAchieveGoals: 'To achieve my goals, I pledge to',
    studyDiligently: 'study diligently by studying',
    decksContinuously: 'decks continuously',
    forDays: 'for ',
    daysPeriod: 'days.',
    submit: 'Submit',
    signHere: 'sign here',
    singleFingerStroke: '(single finger stroke)',
    longestStreak: 'Longest Streak',
    days: 'days',
    decksStudied: 'decks\nstudied',
    flashcardsStudied: 'flashcards\nstudied',
    customBadges: 'Custom Badges',
    dailyStreakBadges: 'Daily Streak Badges',
    weeklyStreakBadges: 'Weekly Streak Badges',
    welcomeBadges: 'Welcome Badges',
    lifetimeBadges: 'Lifetime Badges',
    viewAll: 'View All',
    collapse: 'Collapse',
    // DeckDetails strings
    deckDetails: {
      deckNameCannotBeEmpty: 'Deck name cannot be empty!',
      deckNameAlreadyExists: 'Deck name already exists!',
      errorUpdatingDeckName: 'Error updating deck name!',
      noStatsYet: 'No stats yet! View, study or quiz yourself on this deck in the meantime!',
      createdVia: 'Created via',
      subjects: 'Subject(s)',
      topicsSubtopics: 'Topics/Subtopics',
      educationLevel: 'Education Level',
      examQuiz: 'Exam/Quiz',
      lastReviewedDate: 'Last Reviewed date',
      jobRole: 'Job/Role',
      company: 'Company',
      topics: 'Topics',
      experienceLevel: 'Experience Level',
      masteryLevels: {
        expert: 'Expert',
        proficient: 'Proficient',
        developing: 'Developing',
        beginner: 'Beginner',
        needsPractice: 'Needs Practice',
      },
    },
    // Favorites strings
    favorites: {
      favDecks: 'Fav Decks',
      favFolders: 'Fav Folders',
      favoriteDecks: 'Favorite Decks',
      favoriteFolders: 'Favorite Folders',
      select: 'Select',
      selectAll: 'Select All',
      whoopsWhereDidAllYourFavoriteDecksGo: "Whoops! Where did\nall your favorite decks go",
      whoopsWhereDidAllYourFavoriteFoldersGo: "Whoops! Where did\nall your favorite folders go",
      filterFavoritesBasedOnDateAdded: 'Filter favorites based on\ndate added',
      pleaseChooseAtLeastOneFolder: "Please choose at least one folder if you want to delete or unfavorite.",
      pleaseChooseAtLeastOneDeck: "Please choose at least one deck if you want to delete, add to folder or unfavorite.",
      areYouSureYouWantToDeleteTheseFolders: 'Are you sure you want to delete these folder(s)?',
      areYouSureYouWantToDeleteTheseDecks: 'Are you sure you want to delete these deck(s)?',
      areYouSureYouWantToUnfavoriteTheseFolders: 'Are you sure you want to unfavorite these folder(s)?',
      areYouSureYouWantToUnfavoriteTheseDecks: 'Are you sure you want to unfavorite these deck(s)?',
    },
  },
  Chinese: {
    // Statistics page strings
    statistics: {
      decksFlashcards: '卡片组 / 卡片',
      performance: '表现',
    },
    // Index page (Decks screen) strings
    index: {
      myStudyDecks: '我的学习卡片组',
      myInterviewDecks: '我的面试卡片组',
      select: '选择',
      selectAll: '全选',
      whereHaveAllTheDecksGone: '所有卡片组都去哪了？',
      filterDecksBasedOnDateAdded: '按添加日期筛选卡片组',
    },
    // AddDeckModal strings
    addFlashcardsToDeck: '添加卡片到卡片组',
    addDeckToFavorites: '添加卡片组到收藏夹',
    addDeckToFolder: '添加卡片组到文件夹',
    addDeck: '添加卡片组',
    genAIForm: 'AI 生成表单',
    fileUpload: '文件上传',
    youtubeLink: 'YouTube 链接',
    manual: '手动添加',
    // InterviewStudyToggle strings
    study: '学习',
    interview: '面试',
    // AIDeckCard strings
    cardTypes: {
      behavioral: '行为面试',
      technical: '技术面试',
      brainteasers: '脑筋急转弯',
      'case study': '案例分析',
      others: '其他',
      study: '学习',
    },
    cards: '张卡片',
    // Card component strings
    progress: '进度',
    completed: '已完成！',
    untitledDeck: '未命名卡片组',
    // AIPromptModal strings
    aiPromptTitle: '试试为你量身定制的AI卡片组！',
    loadingAiDecks: '正在加载AI卡片组...',
    noDeckSuggestions: '哎呀！',
    noDeckSuggestionsSubtitle: '暂无推荐卡片组',
    emptyStateFooter: '随着你的练习',
    emptyStateFooterSubtitle: '我们会生成更多推荐！',
    // FolderCard strings
    decks: '张卡片',
    // FormHeaderIcons strings
    clearAll: '清空',
    // KindsOfQuestions strings
    kindsOfQuestionsTitle: '4. 你想多练习哪些类型的问题？（可多选）',
    questionTypes: {
      recall: '回忆问题',
      comprehension: '理解问题',
      application: '应用问题',
      analysis: '分析问题',
      synthesis: '综合问题',
      evaluation: '评估问题',
      problemSolving: '解决问题',
    },
    // QuestionTextBarWithDropdown strings
    companiesStartingWith: '以',
    selectACompany: '选择一个公司',
    noCompaniesFoundStartingWith: '没有以',
    noCompaniesFound: '没有公司',
    loadingCompanies: '正在加载公司...',
    // TypeOfInterviewQn strings
    typeOfInterviewTitle: '2. 你正在准备哪种面试？（选一）',
    interviewTypes: {
      technical: '技术',
      behavioral: '行为',
      brainteasers: '脑筋急转弯',
      caseStudy: '案例分析',
      others: '其他',
    },
    // ActionButtonsRow strings
    cancel: '取消',
    // BottomTextInputModal strings
    editDeckName: '编辑卡组名称',
    done: '完成',
    // DifficultyToggleRow strings
    difficultyOptions: {
      default: '默认',
      again: '重来',
      hard: '困难',
      good: '良好',
      easy: '简单',
    },
    // HeaderIconButtons strings
    searchPlaceholders: {
      decks: '搜索卡片组',
      folders: '搜索文件夹',
      favorites: '搜索收藏',
      default: '搜索',
    },
    sortOptions: {
      name: '名称',
      dateAdded: '添加日期',
      lastModified: '最近修改',
    },
    // NavBar strings
    navItems: {
      account: '账户',
      decks: '卡片组',
      statistics: '统计',
      awards: '奖项',
      stats: '统计',
    },
    // SlidingMenu strings
    viewFolders: '查看文件夹',
    // Folders strings
    folders: {
      folders: '文件夹',
      addToFolders: '添加到文件夹',
      moveToFolders: '移动到文件夹',
      foldersCount: '文件夹',
      select: '选择',
      selectAll: '全选',
      done: '完成',
      whereHaveAllTheFoldersGone: '所有文件夹都去哪了？',
      pleaseChooseAtLeastOneFolder: '如果要删除，请至少选择一个文件夹。',
      areYouSureYouWantToDeleteTheseFolders: '你确定要删除这些文件夹吗？',
      filterFoldersBasedOnDateAdded: '按添加日期筛选文件夹',
    },
    // SlidingMenu strings
    viewFavorites: '查看收藏',
    // AddViewToggle strings
    addFlashcards: '添加卡片',
    viewFlashcards: '查看卡片',
    // DrawableOptionsRow strings
    clear: '清除',
    // FlippableCard strings
    typeHere: '请在此输入！',
    drawHere: '请在此绘图！',
    pressHoldMic: '按住麦克风按钮录音',
    greatReplay: '太棒了！点击下方按钮播放录音',
    clickToTakeOrUpload: '点击此处拍照或上传图片',
    chooseManual: '请选择上方的手动选项',
    cameraPermissionError: '抱歉，我们需要相机权限才能使用此功能！',
    photoLibraryPermissionError: '抱歉，我们需要相册权限才能使用此功能！',
    imageSelectionError: '选择图片时出错，请重试。',
    photoCaptureError: '拍照时出错，请重试。',
    // CalendarModal strings
    calendarSubtitle: '点击"确定"或"选择日期"应用您的选择。',
    today: '今天',
    thisWeek: '本周',
    thisMonth: '本月',
    all: '全部',
    chooseDate: '选择日期',
    // GenericModal strings
    no: '否',
    yes: '是',
    ok: '确定',
    // TabLayout strings
    deleteDecksConfirmation: '你确定要删除这些卡片组吗？',
    noSelectionMade: '未选择任何内容！',
    noSelectionSubtitle: '如果你想删除或添加到文件夹，请至少选择一个卡片组。',
    confirmAddToFolders: '确认添加到文件夹？',
    confirmMoveToFolders: '确认移动到文件夹？',
    unfavoriteConfirmation: '你确定要取消收藏吗？',
    customGoalFormSubmitted: ['自定义目标表单', '已提交！'],
    deleteDeckConfirmation: '你确定要删除这个卡片组吗？',
    deckMovedToFolder: ['卡片组已移动', '到文件夹！'],
    aiDeckSavedSuccessfully: ['AI卡片组', '保存成功！'],
    deckSavedToFolder: ['卡片组已保存', '到文件夹！'],
    deleteFolderConfirmation: '你确定要删除这个文件夹吗？',
    decksAlreadyInFolders: ['你选择的一个或多个卡片组', '已在所选文件夹中！'],
    // AverageGradeThermometer strings
    averageGrade: '平均分数',
    // AverageSpeedTotal strings
    averageTimePerFlashcard: '平均每张卡片用时',
    seconds: '秒',
    // BreakdownByDifficultyPie strings
    breakdownByDifficulty: '按难度分布的卡片',
    noDifficultyData: '暂无难度数据',
    completeSomeFlashcards: '完成一些卡片以查看分布',
    difficultyLabels: {
      again: '再来',
      hard: '困难',
      good: '良好',
      easy: '简单',
    },
    // BreakdownOfDecksFlashcards strings
    breakdownOfDecksFlashcards: '卡组 / 卡片数量分析',
    loading: '正在加载...',
    noDataAvailable: '暂无数据',
    breakdownDecks: '卡组',
    breakdownFlashcards: '卡片',
    breakdownCategoryLabels: {
      study: '学习',
      technical: '技术',
      caseStudy: '案例分析',
      behavioral: '行为',
      brainteasers: '脑筋急转弯',
      others: '其他',
    },
    // GradeChart strings
    gradeChart: '分数图表 (%)',
    day: '日',
    month: '月',
    loadingGradeData: '正在加载分数数据...',
    noGradeDataAvailable: '暂无分数数据',
    studyOrQuizToSeeProgress: '完成一些卡片以查看分布',
    // MoreDetailsStats strings
    moreDetails: '更多详情',
    loadingStatistics: '正在加载统计...',
    moreDetailsDecks: '卡组',
    moreDetailsFlashcards: '卡片',
    moreDetailsStudy: '学习',
    moreDetailsInterview: '面试',
    accumulatedDecks: '累计\n卡组',
    decksInLocalStorage: '本地\n存储卡组',
    totalDecksQuizzed: '已测\n卡组总数',
    accumulatedFlashcards: '累计\n卡片',
    flashcardsInLocalStorage: '本地\n存储卡片',
    totalFlashcardsQuizzed: '已测\n卡片总数',
    accumulatedStudyDecks: '累计\n学习卡组',
    studyDecksInLocalStorage: '本地\n存储学习卡组',
    totalStudyDecksQuizzed: '已测\n学习卡组总数',
    accumulatedInterviewDecks: '累计\n面试卡组',
    interviewDecksInLocalStorage: '本地\n存储面试卡组',
    totalInterviewDecksQuizzed: '已测\n面试卡组总数',
    // ReviewLineGraph strings
    decksFlashcardsReviewed: '已复习卡组 / 卡片',
    loadingReviewData: '正在加载复习数据...',
    noReviewDataAvailable: '暂无复习数据，开始学习以查看进度！',
    reviewDay: '日',
    reviewMonth: '月',
    reviewDecks: '卡组',
    reviewFlashcards: '卡片',
    // SpeedChart strings
    speedChart: '速度图表（每张卡片的平均速度）',
    loadingSpeedData: '正在加载速度数据...',
    noSpeedDataAvailable: '暂无速度数据',
    studyOrQuizToSeeSpeedTrends: '学习或测验卡片以查看速度趋势',
    // Account strings
    signOut: '退出登录',
    username: '用户名',
    user: '用户',
    userId: '用户ID',
    notAvailable: '不可用',
    currentPlan: '当前订阅计划',
    basicPlan: '基础版',
    website: '官网',
    rateAndReview: '评分\n与评价',
    share: '分享',
    termsAndConditions: '条款\n与协议',
    appSettings: '应用\n设置',
    deckSettings: '卡片组\n设置',
    upgrade: '升级',
    signOutConfirmation: '退出登录',
    signOutMessage: '你确定要退出登录吗？',
    shareMessage: '看看 PrepQuest！https://prepquest.app',
    // Awards strings
    goals: '目标',
    achievements: '成就',
    fillInCustomGoal: '在这里填写你\n的自定义目标!',
    toAchieveGoals: '为了实现我的目标，我承诺',
    studyDiligently: '努力学习，通过学习',
    decksContinuously: '天连续的卡组',
    forDays: '持续',
    daysPeriod: '天。',
    submit: '提交',
    signHere: 'sign here',
    singleFingerStroke: '（单指签名）',
    longestStreak: '最长连续天数',
    days: '天',
    decksStudied: '已学习\n卡片组',
    flashcardsStudied: '已学习\n卡片',
    customBadges: '自定义徽章',
    dailyStreakBadges: '每日连续天数徽章',
    weeklyStreakBadges: '每周连续天数徽章',
    welcomeBadges: '欢迎徽章',
    lifetimeBadges: '终身徽章',
    viewAll: '查看所有',
    collapse: '收起',
    // DeckDetails strings
    deckDetails: {
      deckNameCannotBeEmpty: '卡片组名称不能为空！',
      deckNameAlreadyExists: '卡片组名称已存在！',
      errorUpdatingDeckName: '更新卡片组名称时出错！',
      noStatsYet: '暂无统计数据！你可以先浏览、学习或测验此卡组。',
      createdVia: '创建方式',
      subjects: '科目',
      topicsSubtopics: '主题/子主题',
      educationLevel: '教育水平',
      examQuiz: '考试/测验',
      lastReviewedDate: '上次复习日期',
      jobRole: '职位',
      company: '公司',
      topics: '主题',
      experienceLevel: '经验水平',
      masteryLevels: {
        expert: '专家',
        proficient: '熟练',
        developing: '发展中',
        beginner: '初学者',
        needsPractice: '需要练习',
      },
    },
    // Favorites strings
    favorites: {
      favDecks: '收藏卡片组',
      favFolders: '收藏文件夹',
      favoriteDecks: '收藏卡片组',
      favoriteFolders: '收藏文件夹',
      select: '选择',
      selectAll: '全选',
      whoopsWhereDidAllYourFavoriteDecksGo: '哎呀！你所有收藏的卡片组都去哪了？',
      whoopsWhereDidAllYourFavoriteFoldersGo: '哎呀！你所有收藏的文件夹都去哪了？',
      filterFavoritesBasedOnDateAdded: '按添加日期筛选收藏',
      pleaseChooseAtLeastOneFolder: "请至少选择一个文件夹，如果你想删除或取消收藏。",
      pleaseChooseAtLeastOneDeck: "请至少选择一个卡片组，如果你想删除、添加到文件夹或取消收藏。",
      areYouSureYouWantToDeleteTheseFolders: '你确定要删除这些文件夹吗？',
      areYouSureYouWantToDeleteTheseDecks: '你确定要删除这些卡片组吗？',
      areYouSureYouWantToUnfavoriteTheseFolders: '你确定要取消收藏这些文件夹吗？',
      areYouSureYouWantToUnfavoriteTheseDecks: '你确定要取消收藏这些卡片组吗？',
    },
  },
};
